### ISSUE TITLE
Python error at startup

### ISSUE THREAD

**Issue by mesa57** [linuxserver/docker-sabnzbd#112]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Sabnzbd should normally start

## Current Behavior
The container gets into a python error loop

## Steps to Reproduce
1. Just updated the image / container to latest release
2.
3.
4.

## Environment
ARMBIAN 5.46 user-built Debian GNU/Linux 10 (buster) 4.9.103-odroidxu4

**How docker service was installed:**
Via OpenMediaVault 5.6 OMVEXTRA's -> Install docker

## Command used to create docker container (run/create/compose/screenshot)
Portainer : (currently using a lower release version which does work !)
![afbeelding](https://user-images.githubusercontent.com/6350469/129444481-dd304d65-bf39-4db5-806c-a0a2e466027c.png)

## Docker logs

```
PermissionError: [Errno 1] Operation not permitted,
,
Current thread 0xb6fb0460 (most recent call first):,
<no Python frame>,
Fatal Python error: pyinit_main: can't initialize time,
Python runtime state: core initialized,
PermissionError: [Errno 1] Operation not permitted,
,
Current thread 0xb6f8c460 (most recent call first):,
<no Python frame>,
Fatal Python error: pyinit_main: can't initialize time,
Python runtime state: core initialized,
PermissionError: [Errno 1] Operation not permitted,
,
etc

```

My guess is that the problem is caused by switching to ubuntu/focal as base.

**Comment by Roxedus** [comment]
Please post FULL logs.

**Comment by mesa57** [comment]
Sorry I don't know exactly how to do that. The logs keeps repeating above message.
However i did a docker container logs -f  sabnzbd > logs.txt
and it only contained the beginning of the log ?

[logs.txt](https://github.com/linuxserver/docker-sabnzbd/files/6986450/logs.txt)

**Comment by Roxedus** [comment]
Your logs state why this happens. 
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

**Comment by j0nnymoe** [comment]
According to portainer, you're running a build from 2019? 🤔

**Comment by j0nnymoe** [comment]
> Your logs state why this happens.
> 
> ```
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> 
> Your DockerHost is most likely running an outdated version of libseccomp
> 
> To fix this, please visit https://docs.linuxserver.io/faq#libseccomp
> 
> Some apps might not behave correctly without this
> 
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> ```

Well that explains it

**Comment by mesa57** [comment]
I followed that FAQ - option 2.
The package seems to have the right version.

```
Package: libseccomp2
Source: libseccomp
Version: 2.4.4-1~bpo10+1
Installed-Size: 168
Maintainer: Kees Cook <kees@debian.org>
Architecture: armhf
Depends: libc6 (>= 2.4)
Description: high level interface to Linux seccomp filter
Description-md5: 7ee97a8161e83bfebc75870eb92bde51
Multi-Arch: same
Homepage: https://github.com/seccomp/libseccomp
Section: libs
Priority: optional
Filename: pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb
Size: 36904
SHA256: b32d4c62aba5f48c01b41192fd43d5b9cddf1a3b86590960efdfaf33d20700f0
```

**Comment by Roxedus** [comment]
And the version of docker?

**Comment by mesa57** [comment]
Docker version 19.03.2, build 6a30dfc

**Comment by Roxedus** [comment]
That version is too old for the fix, you need to update docker

**Comment by mesa57** [comment]
I understand that then all my containers are lost. 
Sad that you're container is not supporting version 19.03.2

**Comment by Roxedus** [comment]
Neither of those statements are true.

**Comment by j0nnymoe** [comment]
@mesa57 perhaps trying updating docker.

**Comment by mesa57** [comment]
Finally after hours that worked.
