### ISSUE TITLE
RaspianOS support for Sabnzbd Docker container

### ISSUE THREAD

**Issue by ozdeadmeat** [linuxserver/docker-sabnzbd#113]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

RaspianOS support for Sabnzbd Docker container

------------------------------

## Desired Behavior
Sabnzbd docker container working on Raspian OS

## Current Behavior
Sabnzbd docker container does not work on Raspian OS

## Alternatives Considered
If there are a set of dependencies that the base OS needs that the docker container for Sabnzbd needs, they dont seem to be written down anywhere.

**Comment by aptalca** [comment]
#114
