### ISSUE TITLE
Connection Failed with CIFS VFS errors 

### ISSUE THREAD

**Issue by juan9999** [linuxserver/docker-sabnzbd#115]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I'm having an issue with a docker install on ubuntu 20.04 with apparent conflict with network shares.
I have a docker stack that has openvpn, transmission, sabnzb, sonar (all routed through the vpn).
When the stack is not running, my mounted network share drive (where I save my downloads) works great. When the stack is running, I get a bunch of server disconnects within docker, and get a bunch of CIFS VFS errors and slow response/time outs if I try to say do a ls on a NAS share.
When I delete that stack, suddenly the network share works fine again.
This WAS working fine until a few weeks ago (can't rememberI exactly when)

I created a new ubuntu docker host and copied the same config files and ran the stack and had the same issue.

Then I created an alpine docker host, with the same config files and the issue went away!

So I have no idea what the issue is, but it seems like a different unix distro either has a different implementation of docker, or CIFS.
how can I fix/troubleshoot?
------------------------------

## Expected Behavior

It should work
## Current Behavior

CIFS VFS 
## Steps to Reproduce

1. New ubuntu install
2. Set up docker stack
3. Run SAB
4. CIFS errors/ LAGGY network

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by juan9999** [comment]
<img width="587" alt="Screen Shot 2021-10-13 at 9 58 45 AM" src="https://user-images.githubusercontent.com/31065728/137575951-0a4457a3-68df-4aea-bb07-39ae77719eb3.png"
<img width="292" alt="Screen Shot 2021-10-13 at 9 58 29 AM" src="https://user-images.githubusercontent.com/31065728/137575953-f07af7a0-61c9-4754-bdf1-2c3a22eab331.png">
<img width="776" alt="Screen Shot 2021-10-12 at 6 13 29 PM" src="https://user-images.githubusercontent.com/31065728/137575958-e33adec8-2956-4727-b9e8-6518f84bdba6.png">
>

**Comment by drizuid** [comment]
We do not offer any support for making remote mounts work properly. Suggest digging more into how to properly setup cifs (or even nfs). You're welcome to seek help in #other-support on our discord.
