### ISSUE TITLE
No permissions set on download or incomplete-download dirs

### ISSUE THREAD

**Issue by jhall39** [linuxserver/docker-sabnzbd#117]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Setting the download directories to these locations in SABNZBd should work.

## Current Behavior

Attempting to set it on the default image gives an unhelpful error like  "complete_dir directory: /downloads error accessing"
It is happening because the directories are setup with permissions like chmod 000. If you look at it using ls on the system it shows "d---------" on both directories and neither one can be written to or read from by the abc user. To fix it, I had to exec into a bash shell and run chmod 644 on both.

## Steps to Reproduce

1. Install the container
2. login to it and check permissions
3.
4.

## Environment
**OS:** Synology DSM 7
**CPU architecture:** x86_64
**How docker service was installed:** Synology package

## Command used to create docker container (run/create/compose/screenshot)

I just followed the settings here: https://registry.hub.docker.com/r/linuxserver/sabnzbd/

**Comment by jhall39** [comment]
I'm not sure why you would tag it invalid, it's super easy to reproduce.

**Comment by aptalca** [comment]
No, it's not reproducible and you didn't provide any specific info.

`reproducible` does not mean *you* can reproduce it on the same machine with the same command. It means *someone else* can reproduce it with a correct command. You didn't even tell us what parameters you used.

Open a new issue and fill out the template if you really want proper help.

**Comment by jhall39** [comment]
That's okay, I fixed my problem. Just trying to help you.

**Comment by aptalca** [comment]
Help us with what exactly?

**Comment by jhall39** [comment]
As I said in my issue.
Your container has a problem.
There are no read or write permissions on either the /download or /incomplete-download directories.
Anyone trying to use it with the instructions to map those volumes will end up with error messages when they try to assign them in sabnzbd.
That is because sabnzbd can not read or write there.
because the permissions are wrong.
Even if the user and group are set with the right PUID and PGID, the folder has 000 for the permissions so not even the correct user can write there.
I fixed it by doing "docker exec -it linuxserver-sabnzbd2 /bin/bash" and changing it myself with chmod 644 on both dir.
Other people will probably just see that your container doesn't work and install a different one. Or be content to use the download dir in the /config area.

**Comment by j0nnymoe** [comment]
If it was an issue with the container, I would expect a lot more complaints about this.
There are reasons why we ask for the exact details you used for deploying the container and with the information you provided, I'm unable to try and reproduce this issue on our synology. 99% of the time, if you're having permissions issues, its because either the PUID/PGID you've provided doesn't have the correct permissions to the folders you've mounted or you haven't supplied that information at all.
