### ISSUE TITLE
apt-get missing in new build

### ISSUE THREAD

**Issue by PeterPan669** [linuxserver/docker-sabnzbd#127]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
I need Git and FFMpeg inside this image. Hence I was using apt-get in a 90-config file to install both packages, as per this workaround: [https://discourse.linuxserver.io/t/sabnzbd-container-with-ffmpeg/221](https://discourse.linuxserver.io/t/sabnzbd-container-with-ffmpeg/221). It worked before the latest build.
I expect apt-get to be available.

## Current Behavior
apt-get is no longer found. This wasn't the case on the 22nd of February, 2022.

## Steps to Reproduce
1. Build a container based of this image.
2. Open the console.
3. Run apt-get.
4. Gaze at 'command not found'.

**Comment by j0nnymoe** [comment]
This is because the container got rebased to alpine: https://info.linuxserver.io/issues/2022-02-21-sabnzbd/
You will need to adapt your scripts.
