### ISSUE TITLE
Installation of Zip package

### ISSUE THREAD

**Issue by Zheltyy** [linuxserver/docker-sabnzbd#132]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I would like to use Zip to repack the extracted files into one new zip file. this would be done with a .sh script (currently not working: issue #131). So the zip packed would needs to be installed.

## Current Behavior

Zip package is not installed and zip cannot be used.

## Alternatives Considered

If alpine cannot run .sh scripts and issue #131 cannot be solved, then the zip package would also not be needed.

**Comment by thespad** [comment]
You can add packages required for 3rd party scripts yourself using our customisation logic: https://linuxserver.io/custom
