### ISSUE TITLE
bash shell in new Alpine image is unusable

### ISSUE THREAD

**Issue by obelisk3847** [linuxserver/docker-sabnzbd#133]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Existing scripts that worked using the Ubuntu image that were written in bash should continue to work since bash is supposedly supported in the new Alpine-based images. 

## Current Behavior
Existing scripts that worked using the Ubuntu image no longer work as pretty much any command you execute is not found. Have also logged into the container using docker exec -it {container} /bin/bash and have confirmed the shell is not in a good state as it constantly returns /bin/hostname errors.

## Steps to Reproduce
1. Log into the running container in a bash shell
2. Attempt to execute commands such as find or grep

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** : from the official Ubuntu 20.04 repo sources

Container Created using docker-compose

  sabnzbd:
    image: "linuxserver/sabnzbd:latest"
    container_name: "sabnzbd"
    labels: 
      - com.centurylinklabs.watchtower.monitor-only="true"
    volumes:
      - /usr/sbin/sendmail:/usr/sbin/sendmail
      - /usr/bin/nullmailer-inject:/usr/bin/nullmailer-inject
      - /usr/bin/nullmailer-inject.bin:/usr/bin/nullmailer-inject.bin
      - /usr/sbin/nullmailer-queue:/usr/sbin/nullmailer-queue
      - /etc/nullmailer:/etc/nullmailer
      - /var/spool/nullmailer:/var/spool/nullmailer
      - /home/bergang/.sabnzbd:/config
      - /home/bergang:/home/bergang
      - /mnt/ssd/sab_downloading:/incomplete-downloads
      - /mnt/ssd/4k_stage:/4k_stage
      - /mnt/ssd/premiere_stage:/premiere_stage
      - /mnt/ssd/f1_stage:/f1_stage
    network_mode: host
    ports:
        - "8080:8080"
        - "9090:9090"
    restart: always
    environment:
      - SABNZBD_UID=1000
      - SABNZBD_GID=1000
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CONFIG=/config/sabnzbd.ini

## Docker logs
Not applicable

**Comment by Roxedus** [comment]
Please try without the mounted binaries. I think some of those folders Are originally symlinked in alpine

**Comment by aptalca** [comment]
Mapping binaries into system folders is not a good idea and definitely not something we support.

**Comment by obelisk3847** [comment]
That seems to be the problem as removing the mail binary mounts fixed the issue. I guess I can get the script to dump a mail file onto the host filesystem and then write a host cron utility to send it. It must be related to the soft linking in Alpine as Ubuntu does not have an issue with this configuration. 

Please consider this issue closed.
