### ISSUE TITLE
creating folders no longer works 3.5.1 on nas

### ISSUE THREAD

**Issue by Spotter2011** [linuxserver/docker-sabnzbd#143]
from version I am not able to use folders on my nas it gives this error see photo
![Knipsel](https://user-images.githubusercontent.com/18232630/191012626-0adc6728-506f-45d8-98d9-e669f2d8884d.JPG)

log from contianer station on nas

2022-09-19 12:00:07,182::INFO::[_cplogging:213] [19/Sep/2022:12:00:07] HTTP 
Request Headers:
  Remote-Addr: ::ffff:192.168.39.29
  HOST: 192.168.39.222:8080
  CONNECTION: keep-alive
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.42
  X-REQUESTED-WITH: XMLHttpRequest
  REFERER: http://192.168.39.222:8080/sabnzbd/config/folders/
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: nl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
2022-09-19 12:00:11,019::INFO::[notifier:123] Sending notification: Fout - download_dir directory: fout /Downloads/Media/Temp bij toegang (type=error, job_cat=None)
2022-09-19 12:00:11,019::ERROR::[filesystem:395] download_dir directory: fout /Downloads/Media/Temp bij toegang

is there anything i can do all version above 3.5.0 it doesn't work maybe i do it myself i'm wrong can you help me to fix this or is it a bug in the software
![Knipsel1](https://user-images.githubusercontent.com/18232630/191013234-19c2baf4-fbe7-477c-9e26-46e1e3fd1b59.JPG)

thanks in advance greetings spotter2011

**Comment by Spotter2011** [comment]
![Knipsel3](https://user-images.githubusercontent.com/18232630/191013797-d92150fb-a598-4ee6-8a82-737f5503547f.JPG)

**Comment by Roxedus** [comment]
This has nothing of the information we asked for in the template.

**Comment by Spotter2011** [comment]
[linuxserverurl]: https://hub.docker.com/r/linuxserver/sabnzbd



creating folders no longer works 3.5.1 on nas

------------------------------

from version I am not able to use folders on my nas it gives this error see photo
![Knipsel](https://user-images.githubusercontent.com/18232630/191015258-5e89aa38-ae62-4011-9ac6-6bcaf90efef5.JPG)
![Knipsel3](https://user-images.githubusercontent.com/18232630/191015385-bdb76ff1-ef8b-48cd-84d6-c84c54e4ff22.JPG)
is there anything i can do all version above 3.5.0 it doesn't work maybe i do it myself i'm wrong can you help me to fix this or is it a bug in the software



## Steps to Reproduce


install 3.5.1
then try to save folder to version 3.5.0 does this work
Qnap 
Processor
Intel(R) Celeron(R) J4125 CPU
tot 2700 MHz
(4 kernen, 4 threads)
![Knipsel4](https://user-images.githubusercontent.com/18232630/191016240-0b4eb48f-5a2f-41d5-b11c-3bb03d344ca0.JPG)


my english is not that good don't know what is being asked if there is still something missing ask me

**Comment by Roxedus** [comment]
I would need some full logs, rather than the last part you provided in the issue.

**Comment by bokkoman** [comment]
Join discord so we can solve this with more ease.
You're also forgetting the base folder is `/config`
That didn't like correct to me. As well as missing a starting slash at the `map voor verwerkte downloads`.

**Comment by Spotter2011** [comment]
![Knipsel1](https://user-images.githubusercontent.com/18232630/191737101-b5a4a851-b716-4fe1-be2c-efdad4038f20.JPG)
![Knipsel2](https://user-images.githubusercontent.com/18232630/191737103-9fa3edc8-5ee0-47a9-8f5d-500b9a84458a.JPG)
![Knipsel3](https://user-images.githubusercontent.com/18232630/191737105-96df4ff3-3eeb-438d-9263-f8b1bface286.JPG)
![Knipsel4](https://user-images.githubusercontent.com/18232630/191737106-108af94a-6a9c-4793-81cb-0b0ce3ab265f.JPG)
![Knipsel5](https://user-images.githubusercontent.com/18232630/191737109-771b96af-124e-4b04-ad93-04a96b8fc548.JPG)
![Knipsel6](https://user-images.githubusercontent.com/18232630/191737110-a7855f8c-6b69-4946-9260-5b10503b5f0e.JPG)
![Knipsel7](https://user-images.githubusercontent.com/18232630/191737112-617e9693-ba17-403b-aad0-8cc4bdf66116.JPG)
![Knipsel8](https://user-images.githubusercontent.com/18232630/191737113-1a69a7f4-ea60-43a2-8a15-df1d98a1b741.JPG)
![Knipsel9](https://user-images.githubusercontent.com/18232630/191737115-a6868663-e484-47a0-99a3-c60af2e9eee4.JPG)
![Knipsel10](https://user-images.githubusercontent.com/18232630/191737116-b05eaa51-5ed4-4c93-94d6-69e7513a685d.JPG)
![Knipsel11](https://user-images.githubusercontent.com/18232630/191737117-6cf2ec26-0b2f-4656-a05e-810f4cf2e3c0.JPG)
![Knipse12l](https://user-images.githubusercontent.com/18232630/191737099-6e1e3c9e-d86f-41dc-bd53-ceca488a816f.JPG)
[log.txt](https://github.com/linuxserver/docker-sabnzbd/files/9625296/log.txt)

I have added a step-by-step plan to screenshot + the log hope this is enough for you to solve this problem from version 3.5.1 and higher

**Comment by bokkoman** [comment]
@Spotter2011 waarom zit je op zo'n oude versie? Sabnzbd is al bij versie 3.6.1.

`englishs`
why are you still using v3.5.1, sabnzbd is at v3.6.1

**Comment by Spotter2011** [comment]
everything above version 3.5.0 has this problem i can't assign a download folder on my nas that's why i opened this problem so i can update to the latest version

**Comment by bokkoman** [comment]
> everything above version 3.5.0 has this problem i can't assign a download folder on my nas that's why i opened this problem so i can update to the latest version

Come join this:

https://discord.com/invite/Vau8dZ3

**Comment by Spotter2011** [comment]
![Knipsel12](https://user-images.githubusercontent.com/18232630/191740069-a2aff829-7de6-4ac8-8365-40dcee6061d5.JPG)

**Comment by Spotter2011** [comment]
why does this work on version 3.5.0? and not on version 3.5.1 and above

**Comment by bokkoman** [comment]
> ![Knipsel12](https://user-images.githubusercontent.com/18232630/191740069-a2aff829-7de6-4ac8-8365-40dcee6061d5.JPG)

Ja, dat ziet er dus echt niet goed uit.
Je hebt een andere structuur nodig.
Ik neem aan dat je ook sonarr/radarr gebruikt?

**Comment by Spotter2011** [comment]
sonar radar i don't know what that is

**Comment by bokkoman** [comment]
> sonar radar i don't know what that is

what do you do with sabnzdd then? :P

**Comment by Spotter2011** [comment]
use spotnet to control sabnzb to download some through my nas and that it is directly on my nas

**Comment by bokkoman** [comment]
> 

like movies and tv shows?
If so, you're doing it the old fashioned way. A world of automation will open up for you if you start using Sonarr and Radarr.

Start with creating this structure, where `data` is a share

```
data
├── usenet
│  ├── movies
│  ├── music
│  └── tv
```

**Comment by Spotter2011** [comment]
Monday I will create an account with discord I'll be gone this weekend I hope you can help me get it right although I find it strange that everything up to version 3.5.0 works as I have set it up now

**Comment by bokkoman** [comment]
Yeah i can help you, no problem.

**Comment by Spotter2011** [comment]
does this mean i have to change my whole disk in partition ? that's a lot of work isn't there a simpler way to get folder working in version higher than 3.5.0?

**Comment by bokkoman** [comment]
> does this mean i have to change my whole disk in partition ? that's a lot of work isn't there a simpler way to get folder working in version higher than 3.5.0?

No. Existing volumes, just new share

**Comment by Spotter2011** [comment]
![Knipsel12](https://user-images.githubusercontent.com/18232630/191780875-6dfc2e2e-3905-4b8d-810c-ea826071934a.JPG)
![Knipsel13](https://user-images.githubusercontent.com/18232630/191780878-44d250e7-cbac-4ce9-86a7-66227cb8719c.JPG)
![Knipsel14](https://user-images.githubusercontent.com/18232630/191780882-9c9cc1a0-7a2e-4cf4-9551-bdfe607cd4fa.JPG)

**Comment by Spotter2011** [comment]
this is my disk layout now how do i create a new share for the contianers now running contianers in a different partition than the downloads

**Comment by bokkoman** [comment]
> this is my disk layout now how do i create a new share for the contianers now running contianers in a different partition than the downloads

You create a new shared folder (gedeelde map) named `data`.
That's a good start for your new adventure.

**Comment by Spotter2011** [comment]
Can I create a folder in downloads called data. and that will solve the problem?

**Comment by bokkoman** [comment]
> Can I create a folder in downloads called data. and that will solve the problem?

You could.
But if you're going to use sonarr and radarr, it will be a weird structure.

**Comment by Spotter2011** [comment]
then i don't need to add folders in contianer station and i can add them a sabnzb like this

**Comment by bokkoman** [comment]
It doesn't work like that.
Container station is actually Docker.

You create a share named `data`.
Create another folder usenet in there.
That's what you mount in the sabnzbd container.

Look, you have no idea yet what you can do with this all.

I suggest reading the guide i posted earlier.
Maybe watch some YouTube on what sonarr and radarr are.

**Comment by Spotter2011** [comment]
I don't know much about docker indeed and was glad I had it working until theE version 3.5.0 I could just add folders without any problems lick then something has changed in the docker 3.5.1 and higher so it doesn't work anymore very difficult I always use windows and no lunix or anything else I have to stay on version 3.5.0 on my nas if I have to do all kinds of weird things to get it to work

**Comment by bokkoman** [comment]
You don't have to do anything weird.
You only need to understand the basics of docker.
We can fix your problem easily. And even use the latest sabnzbd, since using older versions aren't very secure (if open to internet).

**Comment by j0nnymoe** [comment]
This is outside the scope of what these GitHub issues are for. As @bokkoman mentioned, join our discord and people will be able to help you easier.

**Comment by Spotter2011** [comment]
can you explain to me why it works in version 3.5.0 and not in version 3.5.1 then something must have changed thanks for all the effort you put into it

**Comment by bokkoman** [comment]
> can you explain to me why it works in version 3.5.0 and not in version 3.5.1 then something must have changed thanks for all the effort you put into it

Join discord, and someone is probably happy to tell you, if he or she knows. Since that version is really outdated.
Plus it can be a thing in sab, or the way lsio build the docker container.
