### ISSUE TITLE
Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check

### ISSUE THREAD

**Issue by imthisguymike** [linuxserver/docker-sabnzbd#149]
Created the docker using the commands, on two different hosts, both got this error: Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check

My docker commands:
sudo docker pull lscr.io/linuxserver/sabnzbd:latest

docker run -d \
  --name=sabnzbd \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/New_York \
  -p 8080:8080 \
  -v /docker/appdata/SABnzbd:/config \
  -v /mnt/media/NAS/Downloads:/downloads \
  --restart unless-stopped \
  lscr.io/linuxserver/sabnzbd:latest

Manually going into sabnzbd.ini and host_whitelist (separate multiple hostnames by a comma) "fixes" it, but I would like it to be accessible via the -e or -v, and I couldn't find any documentation to support this.

**Comment by aptalca** [comment]
The link from the error explains it pretty well.

Access via IP the first time, go through the wizard and you can add your host allow list there. Then you can access via reverse proxy or any hostname you set
