### ISSUE TITLE
Start using Python 3.11

### ISSUE THREAD

**Issue by Safihre** [linuxserver/docker-sabnzbd#152]
If everything goes well, Python 3.11 will be released next week. It includes a general 25% performance increase, without us (SABnzbd) having to do anything.
Is there a way for this Docker (that we [recommend](https://sabnzbd.org/wiki/installation/install-unix) as the preferred image) to use the new Python, instead of the one that comes with the base OS?

**Comment by Roxedus** [comment]
I think it would be worth waiting until py 3.11 is released, to see if alpine plans to push that to the alpine 3.16 release, or if it's worth moving the image to the edge release.

**Comment by aptalca** [comment]
I don't think alpine will push the python update to 3.16, but it will likely go into edge and 3.17 will be released with it. We can potentially rebase to edge until 3.17 release as long as there aren't any other issues

**Comment by thespad** [comment]
Can test it out with the nightly branch once it's available in the Alpine repos.

**Comment by thespad** [comment]
Looks like Python 3.11 won't hit a stable build until 3.18. We'll rebase the nightly branch to Edge and 3.11 and see how it performs, we can then take a decision on what to do with unstable/master as 3.18 is 6 months away.

**Comment by j0nnymoe** [comment]
Closing as no further comments needed.
