### ISSUE TITLE
/downloads and /incomplete-downloads are setup for the wrong directory

### ISSUE THREAD

**Issue by OmgImAlexis** [linuxserver/docker-sabnzbd#16]
When running the container for the first time the directories are setup to use `/config/Downloads/complete` and `/config/Downloads/incomplete` instead of the `/downloads` and `/incomplete-downloads` that the docker volumes are mapped to.

**Comment by sparklyballs** [comment]
We don't preload config.ini for sabnzbd and those folders are created in `~` by default when sabnzbd runs for the first time.
home is set to `/config` in the container, hence they are created there.
you have to set the folders in the webui

**Comment by OmgImAlexis** [comment]
Why not use the same directories as what sab uses so that the first time someone runs it they don't have to change them?

**Comment by sparklyballs** [comment]
because people won't want their downloads in the config folder......
