### ISSUE TITLE
[FEAT] Use 7zip instead of p7zip

### ISSUE THREAD

**Issue by woiza** [linuxserver/docker-sabnzbd#166]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please use 7zip instead of p7zip

### Reason for change

- p7zip is very old
- 7zip has some new features, most importantly 7zip uses hardware CPU instructions for AES, CRC-32, SHA-1 and SHA-256 (Intel and ARM64) --> very useful for password protected / encrypted archives
- please see: https://7-zip.org/history.txt

### Proposed code change

```apk add 7zip```

**Comment by aptalca** [comment]
That package is not available in alpine 3.16, but we'll consider switching during a rebase

**Comment by woiza** [comment]
Thanks, much appreciated.

**Comment by aptalca** [comment]
My main reservations are:
- p7zip is an alpine official package, whereas 7zip is a community supported one (community ones may disappear from the repo, but not very likely)
- p7zip has all the standalone binaries ([see here](https://pkgs.alpinelinux.org/contents?branch=v3.17&name=p7zip&arch=x86_64&repo=main)) whereas 7zip is just the main 7z binary ([see here](https://pkgs.alpinelinux.org/contents?branch=v3.17&name=7zip&arch=x86_64&repo=community)). Not sure if sab relies on the other binaries or not

If you can find out about the second point above and confirm that it would work, that would save us a lot of time and speed up the rebase and switch

**Comment by woiza** [comment]
According to Safihre's answer in this thread, sabnzbd uses 7zip for zips:
https://www.reddit.com/r/SABnzbd/comments/qm2bna/how_to_make_sabnzbd_use_7zip_to_unpack_everything/

Source includes 7zip (at least for Windows):
https://github.com/sabnzbd/sabnzbd/archive/3.7.2.zip

Besides, nzbget mentions 7zip in its configuration documentation and sabnzbd and nzbget pretty much do the same thing.
Nzbget UI --> Settings --> UNPACK --> SevenZipCmd:

```
Full path to 7-Zip executable.
Example: /usr/bin/7z.
Similar to option [UnrarCmd] this option can also include extra switches.
If 7-Zip binary is in your PATH you may leave the path part and set only the executable name ("7z" or "7za" on POSIX or "7z.exe" on Windows).
```

I tested it succesfully with the following file:
https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb-7z-instead-of-rar-ea5b7e8fcddd.nzb
which I got from this issue:
https://github.com/sabnzbd/sabnzbd/issues/1305

For my test I used a "custom" nzbget image based on your work (sorry, I don't use sabnzbd yet):
https://github.com/linuxserver/docker-nzbget/commit/5a2e3c7b9b0f3487264176379b8da2305215d675
