### ISSUE TITLE
Feature: Watch and categorie folders

### ISSUE THREAD

**Issue by tiki1980** [linuxserver/docker-sabnzbd#17]
Sabnzbd provides support for watch folders where you can drop a nzb file and it will be picked up after a certain amount of time. The watch folder is not defined as a volume for now

Also sabnzbd provides support for categories. In a categorie you can define target folders for your files that are different then the default. Is it possible to implement for example 10 categorie folders (categorie_1 till categorie_10). There is no real maximum defined for categories but this will be sufficient for the majority of the users.

**Comment by sparklyballs** [comment]
Any additional mounts can be added at runtime by adding additional 
`-v <host-category-folder>:/<category-name` for instance, which is standard docker behaviour.

I don't think adding 10 additional mounts for categories is a viable prospect for those that don't need them.

**Comment by sparklyballs** [comment]
My personal copy of sabnzbd for instance has the following additional mounts added manually for categories.

In unraid via their webui, but the underlying code passed to docker is the same format as in my previous comment

![screen shot 2016-12-19 at 13 16 23](https://cloud.githubusercontent.com/assets/4343808/21314219/b52d2d9a-c5ed-11e6-9448-f77898557a0a.png)


Also on the subject of a watch folder, that would be better suited a pull request.
