### ISSUE TITLE
[FEAT] bump unrar

### ISSUE THREAD

**Issue by thezoggy** [linuxserver/docker-sabnzbd#178]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

with sab 4.x we bumped unrar to 6.21, i still see 6.12 is being used over here and figure i'd call it out to get it bumped
https://www.rarlab.com/rar/unrarsrc-6.2.6.tar.gz

changelog: https://www.rarlab.com/rarnew.htm

### Reason for change

bump unrar

### Proposed code change

change
```
ARG UNRAR_VERSION=6.1.7
```
to
```
ARG UNRAR_VERSION=6.2.6
```

**Comment by thespad** [comment]
Your timing is impeccable, I literally just opened #175 #176 #177 to bump unrar (and switch from p7zip to 7zip)
