### ISSUE TITLE
Zombie process

### ISSUE THREAD

**Issue by adacey** [linuxserver/docker-sabnzbd#18]
I keep seeing that the docker container gets into an unresponsive state, with sabnzbd becoming a zombie process, after leaving the container running for some time. The sabnzbdplus process becomes unkillable and so far the only way I've been able to get it back is to completely kill Docker and restart all of my containers.

Unfortunately, so far the logs are not particularly useful as they just stop when the container hangs. It seems to be related to decoding of files, but a certain number will work.

I also think this is causing my Sonarr container to hang. As it's also getting into a hung state and the timestamps match, so where it's communicating with sabnzbd I suspect it's the same cause, but one thing at a time.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Host OS - Mac OSX Sierra (10.12.2) running Docker for Mac stable channel (1.12.5 - 14777)

**Comment by sparklyballs** [comment]
docker on mac is still somewhat unstable
