### ISSUE TITLE
Fails at restart with todays image, missing sabctools

### ISSUE THREAD

**Issue by FearTheGrackle** [linuxserver/docker-sabnzbd#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules

### Expected Behavior

.

### Steps To Reproduce

start container with latest today

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
```

**Comment by thespad** [comment]
Please complete the issue template, we cannot attempt to troubleshoot an issue without knowing your environment, which image tag you're using, how you are running the container, and full container log output.

**Comment by FearTheGrackle** [comment]
my bad fixing now...
