### ISSUE TITLE
[FEAT] par2cmdline-turbo

### ISSUE THREAD

**Issue by L2501** [linuxserver/docker-sabnzbd#189]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

par2cmdline-turbo instead of par2cmdline
https://github.com/animetosho/par2cmdline-turbo

### Reason for change

par2cmdline-turbo contains big speed improvement over stock, consider replacing

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-mods/tree/sabnzbd-par2cmdline-turbo

Once it's established and stable we'll consider replacing it as the default.
