### ISSUE TITLE
[BUG] SAB_NOTIFICATION_PARAMETERS not respected by nzb-notify

### ISSUE THREAD

**Issue by jeefberkey** [linuxserver/docker-sabnzbd#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A notification using nzb-notify errors with the following line 

```
2023-06-10 10:59:12,052::ERROR::[notifier:375] Notification script returned exit code 1 and output "2023-06-10 10:59:12,045 - sabnzbd-notify - 253 - ERROR - Not enough arguments specified.
```

and no notification is sent

### Expected Behavior

The notification script parameters should be added to the command from SAB_NOTIFICATION_PARAMETERS. There's already a new release ([link](https://github.com/caronc/nzb-notify/pull/96)), so I think it just needs to be updated here.

### Steps To Reproduce

1. Use image tag `lscr.io/linuxserver/sabnzbd:4.0.2-ls111`
2. Try to use the nzb-notify script with a parameter
3. Error

### Environment

```markdown
- OS: Fedora 38
- How docker service was installed: Kubernetes
```

### CPU architecture

x86-64

### Docker creation

```bash
Not relevant
```

### Container logs

```bash
2023-06-10 10:59:11,996::INFO::[api:833] Executing notification script
2023-06-10 10:59:11,997::INFO::[misc:1175] [N/A] Running external command: ['/app/nzbnotify/sabnzbd-notify.py', 'other', 'SABnzbd: Other Messages', 'Test Notification']
2023-06-10 10:59:12,052::ERROR::[notifier:375] Notification script returned exit code 1 and output "2023-06-10 10:59:12,045 - sabnzbd-notify - 253 - ERROR - Not enough arguments specified.
Syntax: sabnzbd-notify.py <Type> <Title> <Message> url1[,url2[,urlN]]
* The <Type> can be one of the following:
	startup: Startup/Shutdown
	pause_resume: Pause/Resume
	download: Added NZB
	pp: Post-Processing Started
	complete: Job Finished
	failed: Job Failed
	warning: Warning
	error: Error
	disk_full: Disk Full
	queue_done: Queue Finished
	new_login: User Logged In
	other: Other Messages
* The <Title> and <Message> are self explanitory. If the <Title> is however left
	blank, then the description of the <Type> is used instead.
* All remaining arguments are treated as URLs. You can also delimit multiple
	URLs in a single string/argument with the use of a comma (,).
"
```

**Comment by thespad** [comment]
Stable and Develop branches haven't built since the upstream changes were made to nzb-notify, so it doesn't support the env. Once they next build it should work as expected.

**Comment by jeefberkey** [comment]
Thanks for the quick response. Does every lsXXX update get a full rebuild?

**Comment by aptalca** [comment]
Yes
