### ISSUE TITLE
missing SABCTools module when using the latest build version 4.0.2. 

### ISSUE THREAD

**Issue by mattman73** [linuxserver/docker-sabnzbd#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing the latest version 4.0.2 using docker there is an error with the missing SABCTools module, I have tried installing the nightly build but this still errors.
The only way I got this image working again was to force a docker tag of 4.0.0.

### Steps To Reproduce

install the latest build using portainer over an existing version so only the image is updated, still using the same volume / config file mapping.

### Environment

```markdown
- OS: Ubuntu 20.04
- How docker service was installed: via cli for Ubuntu.
```

### CPU architecture

x86-64

### Docker creation

```bash
pulled from docker using portainer.
```

### Container logs

```bash
sorry did not copy the log files, if you are still wanting them then I can install the latest build and then get the logs.
```

**Comment by Roxedus** [comment]
https://info.linuxserver.io/issues/2023-05-22-portainer/
dupicate of #188
