### ISSUE TITLE
[BUG] Not all python requirements installed

### ISSUE THREAD

**Issue by dcampillo** [linuxserver/docker-sabnzbd#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest image seems to not contain all requirements:

**Error message after installing the last image:**
`Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders`

**Solution:
`python -m ensurepip --upgrade`
`python -m pip install -r requirements`

This solved the issue, but it is only a temporary solution to have it running.

### Steps To Reproduce

- Deploy latest image
- start the container
- look at the logs
--  `Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders`

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
From docker compose
```

### Container logs

```bash
Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders
```

**Comment by Roxedus** [comment]
Without you filling out the whole template, I am assuming you are using the affected management UIs. https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by dcampillo** [comment]
Well, the docker image for the 4.0.1, just worked out of the box, for several month. It was deployed via Docker Compose. 
I have download the 4.0.2 image via Portainer and rebuilt the container as usual.
