### ISSUE TITLE
Restarting Docker causes port to revert

### ISSUE THREAD

**Issue by phiyuku** [linuxserver/docker-sabnzbd#2]
When restarting the Docker the SABnzbd port is reverting back to Port 8080 even after changing the port in the UI.

**Comment by phiyuku** [comment]
Changing the port in the UI changes the sabnzbd.ini file in the config folder but when you restart the server the port changes back to 8080 but the other settings seem to stick. Even the https port sticks.

**Comment by phiyuku** [comment]
I fixed it. Can you please update run to this:

exec /sbin/setuser abc /usr/bin/sabnzbdplus --config-file /config

the --server 0.0.0.0:8080 is not needed and is overwriting the port when it starts.

Thanks

**Comment by sparklyballs** [comment]
why do you even need to change the port in the webui ?
if you want a different port, just change the external (host side) of the run command

ie -p 9023:8080

**Comment by phiyuku** [comment]
I did try that and I hit something redirecting back to 8080 which lead me to this. Looking back it seems like its only the restart SABnzbd button which isn't too bad. Not sure if there is anything else though.

Thanks

**Comment by lonix** [comment]
Its forced to be port 8080 by design change it in your docker command
rather "-p 5682:8080"
tor. 10. mar. 2016 kl. 05.43 skrev phiyuku <notifications@github.com>:
