### ISSUE TITLE
[FEAT] Use par2cmdline-turbo

### ISSUE THREAD

**Issue by Safihre** [linuxserver/docker-sabnzbd#204]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Replace par2cmdline by par2cmdline-turbo
https://github.com/animetosho/par2cmdline-turbo

### Reason for change

This new version is a drop-in replacement that uses the much faster parpar backend for par2 verification and repair.
It even outperforms Multipar, which was always the (Windows-only) king of performance.
We will also include it in the SABnzbd binary release for macOS and Windows starting with SABnzbd 4.1.0. 
However, since it's a drop-in replacement, it also works with any version of SABnzbd.

It is already included in the `sab-addons` PPA, if that makes it easier: https://launchpad.net/~jcfp/+archive/ubuntu/sab-addons

**Comment by j0nnymoe** [comment]
It can be enabled in our container using this mod: https://github.com/linuxserver/docker-mods/tree/sabnzbd-par2cmdline-turbo

**Comment by aptalca** [comment]
@Safihre  Thanks so much for the heads up. The images are being updated and pushed as we speak.
