### ISSUE TITLE
[BUG] Curl causes high load on Synology devices

### ISSUE THREAD

**Issue by LapinFou** [linuxserver/docker-sabnzbd#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The command `curl -sKl ...` is running as root @100% all the time.
Same issue on the sonarr package.
I rolled back to version **4.1.0-ls141** and this bug is not present.
After Googling the issue, I found this: https://github.com/curl/curl/issues/12517
I'm not a software guy, but it looks like a Alpine issue.

### Steps To Reproduce

Using the latest release, then checking the CPU activity of the NAS (using the `top`command) though a SSH connection.

### Environment

```markdown
- OS:Synology DSM7
- How docker service was installed: Using Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
: "3.8"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.1.0-ls141
    hostname: sabnzbd
    container_name: sabnzbd
    env_file:
      - stack.env
    volumes:
      - /volume1/download:/downloads
      - /volume1/docker/sabnzbd/config:/config
      - /volume1/docker/sabnzbd/scripts:/scripts
    ports:
      - 8080:8080
    restart: unless-stopped
```

### Container logs

```bash
Not relevant. This issue can be observed when login on the NAS through a SSH connection.
```

**Comment by thespad** [comment]
https://info.linuxserver.io/issues/2023-12-30-synology/

**Comment by LapinFou** [comment]
Thanks for the information ! 👍
Happy new year to you.

**Comment by LapinFou** [comment]
For the record, this workaround did work for me: https://www.reddit.com/r/synology/comments/18w7bsp/known_issue_curl_endless_loop_with_3x_kernels/
