### ISSUE TITLE
SabNZBD with Portainer and remote folders (synology nas)

### ISSUE THREAD

**Issue by Larsvb0** [linuxserver/docker-sabnzbd#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing this package using Portainer and remote folders is not working. It gives an error when selecting the rights folders in Sabnzbd due to permissions

### Expected Behavior

Sabnzbd to be able to use remote folders

### Steps To Reproduce

using portaner GUI
1. create volume
2. install package
3. change folders in SABnzbd

### Environment

```markdown
- OS: Deban running Docker and Portainer
- Remote OS: Synology NAS
- How docker service was installed: Using CLI
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=sabnzbd \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 8080:8080 \
  -v /path/to/sabnzbd/config:/config \
  -v /path/to/downloads:/downloads `#optional` \
  -v /path/to/incomplete/downloads:/incomplete-downloads `#optional` \
  --restart unless-stopped \
  lscr.io/linuxserver/sabnzbd:latest
```

### Container logs

```bash
none
```

**Comment by j0nnymoe** [comment]
If you've used the paths you've mentioned above, that won't work with any folder as they're placeholders and you're expected to replace them with your own paths.

**Comment by Larsvb0** [comment]
Here is the sollution:

If you want SABNZBD to be able to use remote folders (for example on Synology NAS) and use portainer you cannot do this through the portainer GUI. Portainers does not allow you to add security information to the paths. 

Here are the steps to make it work:
On Synology:
1. create user
2. give permission to folder and SMB application

On Docker/Portainer use CLI:

1. First create volume:
docker volume create \
 --driver local \
 --opt type=cifs \
 --opt device=//10.0.0.11/downloads \   <-- change dir
 --opt o=username=USERNAME,password=PASSWORD,file_mode=0777,dir_mode=0777 \   <.. change username/password
 --name sabnzbd_nas

2. run package
docker run -d \
    --name=sabnzbd \
    -p 5057:8080 \   <-- change to the port you like
    -p 9092:9090 \
    -v sabnzbd_nas:/sabnzbd_nas \   <-- here it connects to the created volume
    -v /home/sabnzbd/.config/sabnzbd:/config \   <-- this is to have the configuration not create an additional volume
     -e TZ=europe/amsterdam \
    -e PGID=1000 \
    -e PUID=1000 \
    lscr.io/linuxserver/sabnzbd

3. Start Sabnzbd in browser, complete the setup and change the incomplete and complete paths to the folder you assigned in 2.  in this case sabnzbd_nas. You can see the folders in this folders as they are on the NAS.
