### ISSUE TITLE
[BUG] External internet access denied - https://sabnzbd.org/access-denied

### ISSUE THREAD

**Issue by phynias** [linuxserver/docker-sabnzbd#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current release randomly throws 
External internet access denied - https://sabnzbd.org/access-denied

local_ranges is set and it works for a little while then doesn't,. then works again

### Expected Behavior

switching back to 4.2.3 fixes problem

### Steps To Reproduce

run latet image

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run --name=sabnzbd --env=TZ=America/Los_Angeles --env=PUID=1001 --env=PGID=1001 --detach=true linuxserver/sabnzbd
```

### Container logs

```bash
2024-05-02 07:02:21,131::WARNING::[interface:387] Refused connection from: ::ffff:172.18.0.20 (X-Forwarded-For: 192.168.1.3) [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0]
```

**Comment by j0nnymoe** [comment]
This just seems like you need to correctly configure sabnzbd.

**Comment by fabean** [comment]
I'm having the same issue as of three days ago with an instance that has been running without issues for years. I moved back to previous version and still have issue.

**Comment by fabean** [comment]
Fixed my issue, it was an issue with running tailscale on the host machine breaking things for the containers.

**Comment by cospeedster** [comment]
For anyone else who comes here, you probably want to set `host_whitelist`. (https://sabnzbd.org/wiki/extra/hostname-check.html).

**Comment by francoism90** [comment]
You may need to adjust `host` in `sabnzbd.ini` to something like `0.0.0.0` or your IP-adres.
