### ISSUE TITLE
[FEAT] Don't bundle nzb-notify

### ISSUE THREAD

**Issue by NLZ** [linuxserver/docker-sabnzbd#225]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Stop bundling nzb-notify

https://github.com/linuxserver/docker-sabnzbd/blob/b351cd5b2f5b5877bfe304e0b82e266776e6d49a/Dockerfile#L70

Would be a breaking change, probably better to announce it

### Reason for change

As of 4.3.0 SABnzbd has Apprise integrated into it, making nzb-notify obsolete

https://github.com/sabnzbd/sabnzbd/releases/tag/4.3.0

**Comment by aptalca** [comment]
Does it hurt to keep it for a bit? We can do an announcement first and add a log entry about its deprecation and future removal.

**Comment by thespad** [comment]
We're coordinating with the Sab devs to make sure we don't pull it out from under a bunch of users who depend on it. The nightly tag has had it removed for a few weeks and we'll probably look to remove it from the stable branch after the next point release as there are still a couple of apprise bugs to be worked out.

**Comment by thespad** [comment]
This was removed as of https://github.com/linuxserver/docker-sabnzbd/pull/229
