### ISSUE TITLE
Add SAByenc to container

### ISSUE THREAD

**Issue by avluis** [linuxserver/docker-sabnzbd#23]
Taken from: https://sabnzbd.org/wiki/extra/sabyenc.html

> In SABnzbd 2.0.0 we introduce a new module called sabyenc to increase the download speed on CPU-limited devices.
>The Windows- and MacOS-packages of SABnzbd automatically contain that module.
>On other platforms (like Linux) you have to make sure the module is installed.

Is it possible to include this on the container by default?

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by sparklyballs** [comment]
it's in the unstable branch already
sab 2.0 is only alpha at the moment.

**Comment by avluis** [comment]
Awesome! Good to know!
