### ISSUE TITLE
Use a compiled version of multicore par2

### ISSUE THREAD

**Issue by jeroenj** [linuxserver/docker-sabnzbd#24]
The [SABnzbd v2.0.0](https://github.com/sabnzbd/sabnzbd/releases/tag/2.0.0RC1) release notes read that it's now easier to install a multicore version of par2:

> Multicore Par2 is now easily available through the PPA and other channels:
https://sabnzbd.org/wiki/installation/multicore-par2

This would mean that the compilation step of par2 in the Dockerfile could be replaced by installing par2 from that ppa. This would simplify the Dockerfile. 👌 

I'd be happy to open a pull request for this.

**Comment by sparklyballs** [comment]
we already do that in the unstable branch
https://github.com/linuxserver/docker-sabnzbd/blob/unstable/Dockerfile#L27

plan to incorporate it into the master branch when 2.0 goes full release.

**Comment by jeroenj** [comment]
Ah nice. I forgot to look in there. 🤦‍♂️
