### ISSUE TITLE
What is the dockeruser when installing on Docker for macOS?

### ISSUE THREAD

**Issue by usharf** [linuxserver/docker-sabnzbd#25]
Following the guide for initial setup on current version of Docker for macOS, I'm not sure which user I should setup the container when I initially create it.

**Comment by CHBMB** [comment]
In Linux (Not a MacUser)  you just create a new user/group that aren't root.

**Comment by sparklyballs** [comment]
the id command works from the terminal in macos same us it would do in linux.

use the values shown there for uid and gid on your chosen user.
