### ISSUE TITLE
Update our logo

### ISSUE THREAD

**Issue by Safihre** [linuxserver/docker-sabnzbd#30]
Just a minor thing, but I was hoping you could update our logo on all the dockers?
The SVG is available here:
https://sabnzbd.org/images/logo-full.svg
👍

**Comment by sparklyballs** [comment]
hi there @Safihre , is it possible you have it as .png on a transparent background ?

**Comment by Safihre** [comment]
![logo-full](https://cloud.githubusercontent.com/assets/5703454/25221632/106cfcc6-25b6-11e7-950d-e1ae43a9c0a7.png)

**Comment by Safihre** [comment]
Or if you want a different resolution:
https://cloudconvert.com/svg-to-png
😉

**Comment by sparklyballs** [comment]
i've updated the image in our repository where we store them for our README's etc.

I'm not sure how long any cacheing issues will continue to show the older logo for.

**Comment by sparklyballs** [comment]
edit, the dockerhub is showing the new logo already, it's just github that is showing the older one now.

**Comment by Safihre** [comment]
👍 Perfect

**Comment by CHBMB** [comment]
Github is showing the correct logo too now....
