### ISSUE TITLE
invalid reference format

### ISSUE THREAD

**Issue by musician2000** [linuxserver/docker-sabnzbd#31]
Hi I am using windows 7 with Docker(Virtual Box Host), I am new to docker but have tried many combinations and cant get this to work. I keep getting invalid reference format, and have no idea how to debug what that error means?

$ docker create --name=sabnzbd \ -v C:\DockerApps\Sabnzb\Config:/config \ -v C:
\DockerApps\Sabnzb\Downloads:/downloads \ -v C:\DockerApps\Sabnzb\Incomplete:/i
ncomplete-downloads \ -e PGID=197121 -e PUID=197608 \ -e TZ=Europe/London \ -p
8080:8080 -p 9090:9090 \ linuxserver/sabnzbd
invalid reference format

I have tried changing \ to / still no luck.

Any ideas what this error means?

**Comment by j0nnymoe** [comment]
Closing issue as you had resolved this is IRC :)

For ref:  '\drive\path\to'
