### ISSUE TITLE
Feature Request: python requests

### ISSUE THREAD

**Issue by LoveBootCaptain** [linuxserver/docker-sabnzbd#34]
hey there,

would be absolute awesome if you could provide the python module requests as well inside the container.
it is needed to post-process (for e.g. sickbeard/sickgear/sickrage etc.) after downloading.

the workaround with:

`apt-get update`
`apt-get install python-pip`
`pip install --upgrade pip`

from inside the container and than:

`pip install requests`

does the job quite well but would be great to have it onboard.

kind regards from berlin

Stephan

**Comment by Natteverf** [comment]
I hope that i am not speaking out of turn here, but take a look at: 
https://github.com/Natteverf/docker-sabnzbd

**Comment by 69ScubaDiver** [comment]
Hi 
Was this suggestion adopted ?
