### ISSUE TITLE
Specifying 0.0.0.0 on command line

### ISSUE THREAD

**Issue by Ghent** [linuxserver/docker-sabnzbd#35]
https://github.com/linuxserver/docker-sabnzbd/blob/fa6ce38657f22d9c7af0b40b0e03708c1417eb04/root/etc/services.d/sabnzbd/run#L5

Is there a particular reason for this?  It overrides whatever setting someone configures in their configuration to listen on and exposes the software to the world on public interfaces.  Not very secure... :\

**Comment by sparklyballs** [comment]
if your putting sabnzbd on a public interface with no security then you have bigger things to worry about surely ?

**Comment by Ghent** [comment]
I'm trying NOT to put it on a public interface, but because this line is here, I can't bind it to 127.0.0.1, since the --server tag overrides the config.

**Comment by aptalca** [comment]
You can put it on a custom docker network. 

I'm assuming you're trying to set it up on a vps or the like, and you will access it through a reverse proxy?

**Comment by sparklyballs** [comment]
the port 8080 will be as open to the host whatever the setting internally in the docker container as locahost/127.0.0.1 are relevant to the container internally only and not the host

port 8080 will be open to the host machine and any security from external forces are set at the host level

**Comment by Ghent** [comment]
Access through a reverse proxy is correct.  Regardless of the network it's on, it's purely my humble opinion that overriding the user's config with the command line argument is removing the ability for the user to configure the software how they see fit.  For hours, I couldn't figure out why every time I changed my config, it would reset the listen host back to 0.0.0.0 every restart.  Finally I started digging through the repo here to see if I could find an answer.

I'm not trying to come across rude or blaming, just wondering if there's any upside to that behavior.  With no config, it would listen on 0.0.0.0 anyways, and then with a config, wouldn't we want it to respect what the user does in their config?

I'm very appreciative of the fact that you take time out of your day to make and maintain this software for all of us to use.  Just offering up some thoughts and ideas on how to help.  I'm happy to fork and PR if you/folks agree.

**Comment by sparklyballs** [comment]
you map the port externally to 127.0.0.1 not internally 

ie -p 127.0.0.1:8080:8080 in the docker run command

then that port is only exposed to the HOST. 

127.0.0.1 inside the container would bind it to the container itself and it would not be reachable from the host

**Comment by Ghent** [comment]
So, just making sure I understand the totality of the situation, sabnzbd by default listens on localhost, so this directive on the command line ensures that on initial install, if the user doesn't use host networking, the container will be accessible through the port mappings as needed?

If I have that right, then I understand why it is here and thank you for your explanation. :)

**Comment by aptalca** [comment]
That is correct. You can think of the docker container as a mini VM that shares the kernel with the host. It has its own network interface and such. The docker run/create options provide links between the host and the container through mapping volumes, ports, etc. In this case, any network or port option you control in the sabnzbd gui only has effect inside the container. For instance the port that is selected for the gui, 8080, is only the port inside the container. The mapping makes it accessible on the host at whatever port you map it to. So you're really not supposed to change the networking settings in the sab gui because then it will break things

**Comment by Ghent** [comment]
@aptalca yes, understood behind the purpose and use of docker.  The intent of my original question was to understand the decision of forcing the contained software to listen on all interfaces within the docker.  The nature of this question is because docker allows host networking, and a lot of people use it because of its ease of use.

This leads them to knowingly or unknowingly exposing their sabnzbd installation on a possible public interface and it's difficult to change and difficult to understand how to change it.  You cannot go into the configuration of sabnzbd and change it, as the command line argument will silently override anything you put in the configuration itself.  So, the only two methods are for people to modify the running docker (which docker discourages) or to use another form of networking, which may not work for them, for any number of reasons, ignorance being one of them.  In any case, I would hope the docker itself is designed in such a way to protect the user rather than expose them, if possible.  You could say they should know better, but we all had to learn at some point, and we all didn't know what we didn't know.

All that said, I appreciate the explanation given by @sparklyballs and can understand the decision he made in an effort to provide easier functionality.  I wanted to ask in case it had not been considered; trying to be a friendly and helpful user of the docker giving some feedback. :)

**Comment by Ghent** [comment]
Yikes, my page had not updated that this issue had been closed, my apologies for popping it open again!
