### ISSUE TITLE
New packages needed for 2.3.0

### ISSUE THREAD

**Issue by daften** [linuxserver/docker-sabnzbd#36]
Feature request: new packages are needed for 2.3.0, add those if needed. ANd maybe also add a apt-get update on container boot, some other docker containers  do this and it's very handy for software like this IMO.

**Comment by aptalca** [comment]
Can you specify which packages are needed?

Instead of an apt-get, we refresh the images weekly (every Friday night). Simply recreate the container. That way, each tagged image is the same.

**Comment by daften** [comment]
i think python-yenc was one of them for sabnzbdplus (could be ok for new installs). and par2 was also needed.
I use docker on a synology nas. Recreating a container is a bit more cumbersome there than via cli, but i'll try that approach. Thanks for the extremely quick reply (and the containers) :)

**Comment by sparklyballs** [comment]
Get:2 http://ppa.launchpad.net/jcfp/sab-addons/ubuntu xenial/main amd64 python-sabyenc amd64 3.3.1-0ubuntu1~jcfp1~16.04 [7,002 B]
Install log latest build with 2.3 sab



Linux/NAS: Update of SABYenc to version 3.3.1 is required.

Requirements from sab change log for the release.  


And we compile par2

**Comment by aptalca** [comment]
Thanks, we will look into the packages.

In the meantime, you can give portainer a try. It's a really nice gui for managing containers. They recently added functionality for editing containers and recreating them with the same options. It's easy to just have it pull the new image and do a single click recreate.
