### ISSUE TITLE
New build for PPA Update to fix issues 

### ISSUE THREAD

**Issue by Fish2** [linuxserver/docker-sabnzbd#37]
Can you do a build update and check that the PPA update won't brake anything 

More info https://github.com/sabnzbd/sabnzbd/pull/1061

**Comment by sparklyballs** [comment]
our jenkins will trigger a refresh build on this image tomorrow evening between 11pm and midnight uk time

**Comment by Fish2** [comment]
I have tested the new docker image and all fixed now
