### ISSUE TITLE
Port resets on each restart

### ISSUE THREAD

**Issue by spacecakes** [linuxserver/docker-sabnzbd#40]
I'm running the `latest` SABnzbd in Docker and I've got a UniFi Controller app that needs to run at host with port `8080`, so I've set SABnzbd to run on another port. But it resets each time it starts so that it won't ever go anywhere else than to port `8080`. 

Does not matter if I change the `sabnzbd.ini` or in the GUI—it always returns to 8080. This means I can't have my containers running at the same time.

Is there anything in the Docker image that does this?

**Comment by j0nnymoe** [comment]
You don't need to change the port within the container. You just need to change the left hand side port on this flag `-p 1234:8080`.

**Comment by sparklyballs** [comment]
don't change the port in the gui 

change the port as per instructions here 

https://github.com/linuxserver/docker-sabnzbd#parameters

-p a port:8080

**Comment by spacecakes** [comment]
Thanks. Does that require bridged networking? I run it on Synology and I found that interactions with other apps don't work properly when I don't let SABnzbd run on host networking.

**Comment by sparklyballs** [comment]
then you haven't set those other apps up correctly

it does require bridge mode and i run my sabnzbd instance in bridge mode and it interacts with everything i have thrown at it

**Comment by spacecakes** [comment]
> then you haven't set those other apps up correctly

Well, that is probably correct. I've been at it all day and just decided to go back to host networking.

**Comment by sparklyballs** [comment]
a better place to seek advice and help setting things up would probably be our discord channel 

https://discord.gg/YWrKVTn

(no actual talk about any pirate content (movies etc) though please)

**Comment by j0nnymoe** [comment]
Do you have an option for "Nat" when setting up the containers? I have to select NAT on QNAP to do bridge networking.

**Comment by spacecakes** [comment]
I can only choose hosts or bridge. Bridge would be preferable to have more control over ports bindings, but downloads fail to start and API integrations doesn't seem to work properly either in bridged mode.

No doubt a config issue on my part, but I am new to this. It's much simpler to just change the port for SABnzbd and have it plugged into host networking. Too bad it changes back.

Will check out discord. Thanks.

**Comment by spacecakes** [comment]
Figured out why I was having issues with container interoperability on a bridged network. I run this on a Synology NAS so setup may vary. When using a bridged network, you need to link containers for them to access each other. For example, link Sonarr to SABnzbd with an alias. I linked Sonarr to SABnzbd with the alias `sab` and put in `sab:8080` (which is the internal port) in Sonarr. Works perfectly. 

Hope this helps someone else having this issue.
