### ISSUE TITLE
SABnzbd Host reset to 0.0.0.0 on every configuration change

### ISSUE THREAD

**Issue by dooz127** [linuxserver/docker-sabnzbd#42]
I'm running the image on a Synology, and every time I make a configuration change, the host gets reset to 0.0.0.0.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
Why are you trying to change it?

**Comment by j0nnymoe** [comment]
This is by design, you don't need to change the host ip within the container. All explained here: https://github.com/linuxserver/docker-sabnzbd/issues/35
