### ISSUE TITLE
Download folders specified in the docker volume config aren't used and are instead set to default. 

### ISSUE THREAD

**Issue by bobsupercow** [linuxserver/docker-sabnzbd#46]
There is currently no config file generated / copied to the installation directory.
The scripts create the local `/downloads` and `/incomplete-downloads` and correctly set the permissions, but since there is no config file with those paths set, they are not used. 

Instead they default to the installation defaults specified here: 
[https://sabnzbd.org/wiki/advanced/directory-setup](url)

Per the SAB wiki 

> The paths of the log_dir, admin_dir will be relative to the location of the INI file unless a fixed path is set.
The download_dir, complete_dir, dirscan_dir are relative from the current users home directory. 

> NOTE You can set fixed paths such as D:\Downloads, or /Volumes/nameofdrive/Downloads. However, the path must be accessible to SABnzbd when it is launched otherwise it will be reset to the default path.

Since the HOME ENV is set to `/config`, these are defaulted to `~/Downloads/incomplete`, which are absolute paths within the docker image of `/config/Downloads/incomplete` and `/config/Downloads/complete` instead of `/downloads `and `/incomplete-downloads` as intended. 

Fix seems pretty simple, write to the sabnzbd.ini file to set the variables:
```
download_dir= \incomplete-downloads
complete_dir= \complete-downloads
```
Current workaround is to just manually set these variables in the WebUI for SAB, since they save to the .ini which persists through redeploys.

**Comment by sparklyballs** [comment]
just set it in the webui

**Comment by jshank** [comment]
Seriously, if you aren't going to honor the configuration variable, don't list it on the front page.

**Comment by aptalca** [comment]
What configuration variable? We only suggest a volume mapping. That's not a configuration variable. You can map whatever folder you like and set whatever location for downloads you like.

**Comment by jshank** [comment]
| Parameter | Function |
| :----: | --- |
| `-v /config` | Local path for sabnzbd config files. |
| `-v /downloads` | Local path for finished downloads. |
| `-v /incomplete-downloads` | Local path for incomplete-downloads. |

Downloads are instead stored in `/config/Downloads/complete` by default.

**Comment by sparklyballs** [comment]
that is set by sabmznd as a subfolder of the home folder, and not in our control. 

we give a mount point of /downloads , you set that in the webui, job done.

**Comment by sparklyballs** [comment]
and as @aptalca has already said, it's a volume mounting not a configuration for the app.

**Comment by jshank** [comment]
Maybe a caveat that you will still need to manually define the folder path in the application. `Local path for finished downloads.` sure makes it sound like this is where the output will end up based on the volume setting.

**Comment by jshank** [comment]
Could you not run `sed` against `sabnzbd.ini` to modify the defaults or is that file not created until the wizard is run?

**Comment by aptalca** [comment]
@jshank it's your responsibility to configure the app the way you like. Sabnzbd already forces you to go through the wizard the first time you connect to it's webgui.

**Comment by thelamer** [comment]
If you have a programmatic way of doing this that will generate a functioning sabnzb config using env variables to bypass the entire wizard setup than PR it in. 

I must warn you though that it has to be future proof, the reason this is how initial setup works in this container is because the config does not exist until after the first run from the web UI. We are not going to have some deamon process sitting waiting for a user to finish the wizard to potentially auto swap a single value in it. 

I can understand it is frustrating to have your issue closed so quickly, but this is not the first time we have fielded this question in this repo, trust us it works like this for a reason.

**Comment by glacialcalamity** [comment]
Sorry, I am frustrated with this lack of support for ENV relationship support.  I have to now complete 2-3 different steps through scripts and automation to ensure it can see my Windows share through variables I have set.  I agree with @jshank and believe this should be included.

Anyways, scripting and manual checks was the workaround for this while other container communities give you this option.

**Comment by aptalca** [comment]
What does this have to do with Windows shares 
specifically and what scripting are you talking about?

Set your /downloads mount to whatever folder on host you want, and select /downloads in the gui wizard.

We get frustrated with vaguely described issues and venting even though we explained our methods and upstream related shortcomings clearly.

**Comment by glacialcalamity** [comment]
I apologize for then.
