### ISSUE TITLE
nzbTomedia Issues

### ISSUE THREAD

**Issue by HPMSGEN8** [linuxserver/docker-sabnzbd#47]
Hi Team,

I am running this on Synology DSM 6.1.7-15284 Update 2. I keep on getting issues with nzbToMedia.

Is there something i need to do to get this to work. A Folder i need to mount or setup.

I am using this one - https://hub.docker.com/r/linuxserver/sabnzbd/ 

Any advice please. 

Thanks

**Comment by bobpaul** [comment]
What did you end up doing to add the [nzbtomedia scripts](https://github.com/clinton-hall/nzbToMedia)?

I found a [related issue on the archived nzbget project](https://github.com/linuxserver/docker-nzbget/issues/18) and it seems the options are:

- write your own `Dockerfile` that extends the sabnzb image by adding scripts
- On the host create a folder containing nzbtomedia and mount that into the container (could be an existing volume, such as `:/config`)
- Make an image that contains `nzbtomedia` and run it using the [sidecar pattern](https://medium.com/bb-tutorials-and-thoughts/kubernetes-learn-sidecar-container-pattern-6d8c21f873d). This is the most complex (I think you'd need a to make a daemon that sab can trigger and add a script in the sab container to trigger it.

The first option is clean and good if sab is the only container that needs nzbtomedia. The 2nd and 3rd options are good if you want nzbtomedia in multiple containers (perhaps you run transmission, too). The 3rd is more to maintain, but would be a good option if someone were to create it and maintain it as its own project. The benefit here is that users can update nzbtomedia with a `docker pull` or `docker compose pull` just like everything else

I'll probably look into the 2nd option when I get bored.

**Comment by j0nnymoe** [comment]
You're reading/commenting on nearly 5+ year old issues. If you want to customise the container, use this: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
