### ISSUE TITLE
Folder /incomplete-downloads keeps disappearing

### ISSUE THREAD

**Issue by boyd91** [linuxserver/docker-sabnzbd#48]
Every once in a while SABnzb gives me the error (on adding new nzbs) "Cannot create directory /incomplete-downloads". This is because the folder actually disappears (as well as the mapped folder on my host).

Only deluge does use the hosts 'incomplete-downloads' folder next to SABnzb. But I've used deluge for months without the folder dissappearing. It happend three times already since I installed this container two days ago.

OS: UNRAID

![unraid container setup](https://i.imgur.com/SMjnVSA.png)

**Comment by sparklyballs** [comment]
place a dummy dot file (something like .hidden) in the incomplete folder and it will stop things like sonarr , radarr, couch (or whatever secondary app processes the files) from deleting the path.
