### ISSUE TITLE
Docker is crashing

### ISSUE THREAD

**Issue by darthvader2310** [linuxserver/docker-sabnzbd#5]
When I restart by docker container it stops with the following in the log
Reading package lists...
stdout
16:39:20
E: Unable to correct problems, you have held broken packages.
stderr
16:39:20
*** /etc/my_init.d/20_apt_update.sh failed with status 100
stderr
16:39:20
stderr
16:39:20
*** Killing all processes...

**Comment by deevus** [comment]
Same here

**Comment by CWDN** [comment]
To fix this, I had to stop/remove the container, delete the image and then create the container again.

**Comment by mrchops1024** [comment]
Just had this start happening too. Had to remove the container AND the image, then re-create.

**Comment by darthvader2310** [comment]
thanks this helps
