### ISSUE TITLE
Add lxml python module?

### ISSUE THREAD

**Issue by blysik** [linuxserver/docker-sabnzbd#57]
You add a few commonly used python modules to assist with scripts.  Could you consider adding lxml?  Note that it works well with another module you already install: pynzb.

Thanks!

**Comment by thelamer** [comment]
Is there a specific script that has this as a dependancy? The ones we added were to support very popular notification scripts.

**Comment by blysik** [comment]
Nothing third party that I'm aware of.  I use it in some custom sabnzbd scripts, and was investigating a clean way to install lxml myself.  (Do I fork this project, and create my own container,  do I pip install it after the fact every time, etc..)

I figured it was worth asking here if it could be added.

Thanks for the quick response.

**Comment by thelamer** [comment]
you could mount in a config file like this to run on boot with custom logic: 
```
-v /path/to/your/script.sh:/etc/cont-init.d/30-install-deps
```
To keep things lean we rip out pip on the final images so you would need to have it contain something like this (don't copy and paste just spitballin here) 
```
#!/usr/bin/with-contenv bash

if [ ! -d /usr/lib/python2.7/dist-packages/lxml ] ; then
  apt-get update && apt-get install -y python-pip
  pip install --no-cache-dir lxml
fi
```

**Comment by blysik** [comment]
Ah, interesting!  Thanks for that suggestion.
