### ISSUE TITLE
Renaming/moving folders/files with spaces other characters in names

### ISSUE THREAD

**Issue by psyciknz** [linuxserver/docker-sabnzbd#62]
Got a working Sab instance on an amd64 machine.  Some files contain spaces and /or square brackets and seem to fail.
Example '/incomplete-downloads/Issue.019.[Jun.2019].1/Issue 019 [Jun 2019].pdf'

Both incomplete and complete are on the same hdd of the host, and I was able to confirm that if i exec'd into the container, and add quotes around the entire name that I could copy the file.

SAB reports a permission error....but I was able to do it in the container, so I don't think that's the issue.

I also have the sabnzbd option of replace spaces with underscores on, but that doesn't seem to be taking effect.

Any one else seen this behaviour?

**Comment by CHBMB** [comment]
I'm not entirely clear on what the issue is?  If it's a permissions issue make sure that the folders you've mapped are fully accessible by the user you've set in PUID, which is the whole reason we have a template for issues, so we can get that information.

**Comment by psyciknz** [comment]
It was a permissions error.  For future reference, how can a user exec into a container as the same user that the application in the container runs?

When figuring this out, I was able to copy from the source to the destination, but sabnzbd the application could not.

Would I have to exec into the container and su as the puid user?

**Comment by aptalca** [comment]
You should not be exec'ing into the container. Just set your PUID and PGID correctly and you won't have permission issues

**Comment by CHBMB** [comment]
More to the point, if you actually provided the information we asked for in the template, and that I asked you for again, we might be able to actually point out where you're going wrong......

As @aptalca says, PUID and PGID are your friend.
