### ISSUE TITLE
[Support] Sabnzbd Docker with Synology NAS

### ISSUE THREAD

**Issue by jared-bloomer** [linuxserver/docker-sabnzbd#65]
I am trying to standup the latest version of the Docker container and I am consistently getting an error about not being able to create /datafir/config.ini when the file exist. I would think if it existed then it would just read it and use it. 

Host OS: CentOS 7.6.1810

Create Command: 
docker create --name=sabnzb -p 8080:8080 -p 9090:9090 -v /config/sabnzb/datadir:/datadir -v /sabnzb/complete:/datadir/Downloads/complete -v /sabnzb/incomplete:/datadir/Downloads/incomplete -e TZ=America/New_York -e PUID=1026 -e PGID=100 -e CONFIG=/datadir/config.ini -e SABNZBD_UID=1026 -e SABNZBD_GID=100 sabnzbd/sabnzbd

Docker Log: 
SABnzbd settings
================
  User:       sabnzbd
  UID:        1026
  GID:        100
  Config:     /datadir/config.ini
Updating UID / GID... [DONE]
Set permissions... [DONE]
Get listener port... [8080]
Starting SABnzbd...
Fatal error:
  Cannot create INI file /datadir/config.ini
Specify a correct file or delete this file.

I have banged my head on this for a week now. Any Guidance would be appreciated.

Thanks,
Jared

**Comment by aptalca** [comment]
You're not using our image. Ours is `linuxserver/sabnzbd`

**Comment by jared-bloomer** [comment]
ah doh. My bad

**Comment by aptalca** [comment]
That looks like a third party repo pretending to be official. Same user created docker hub accounts called sabnzbd, couchpotato, sickbeard, sickrage, etc. and pushing images to them that look like official images.

https://github.com/domibarton

**Comment by ovizii** [comment]
May I join this conversation? I am using the correct image linuxserver/sabnzbd and am getting the same error:

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

Fatal error:
  Cannot create INI file /config/sabnzbd.ini
Specify a correct file or delete this file.

Fatal error:
  Cannot create INI file /config/sabnzbd.ini
Specify a correct file or delete this file.
```

I then tried entering the containers shell:

```
docker exec --user abc -ti sabnzbd bash
bash: /config/.bashrc: Permission denied

id abc
uid=1000(abc) gid=1000(abc) groups=1000(abc),100(users)

ls -al /config/
ls: cannot access '/config/.': Permission denied
ls: cannot access '/config/..': Permission denied
ls: cannot access '/config/test': Permission denied
ls: cannot access '/config/.bash_history': Permission denied
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
-????????? ? ? ? ?            ? .bash_history
-????????? ? ? ? ?            ? test

ls -al
total 250
drwxr-xr-x   1 root root  4096 Dec 13 17:07 .
drwxr-xr-x   1 root root  4096 Dec 13 17:07 ..
drwxr-xr-x   1 abc  abc   4096 Dec  4 17:12 app
drwxr-xr-x   1 root root  4096 Feb  4  2019 bin
drwxr-xr-x   2 root root  4096 Apr 24  2018 boot
drw-rw----   2 abc  abc      4 Dec 13 17:11 config

```

I'm confused. I created the config folder outside the container did a chown -R 1000:1000 config followed by a chmod -R 660 config...

###edit###
fixed with a chmod -R 770 config

for whatever reason the error above about not being able to "Cannot create INI file /config/sabnzbd.ini" meant the folder needed the executable bit !?!?!
