### ISSUE TITLE
How to autostart miredo within sabnzbd docker container?

### ISSUE THREAD

**Issue by famewolf** [linuxserver/docker-sabnzbd#66]
I've done and apt-get update and installed miredo to allow support for ipv6 usenet servers.  I've done a commit of the container to an image and am making sure to use that image for my container however I can't figure out how to make miredo auto start when the container and sabnzbd start up.  Can someone point me in the right direction?  A quick /etc/init.d/miredo start works fine from the console manually.  I've considered adding that line into the sabnzbd script.  the /etc/default/miredo file appears to be telling it to autostart but it doesn't happen.

**Comment by j0nnymoe** [comment]
Use this: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by famewolf** [comment]
Thank you for taking the time to point me in the right direction!  That solution was much simpler then the road I was going down.
