### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by nitrag** [linuxserver/docker-sabnzbd#67]
Python 2.7 is EOL in 1 month, when can we see python 3? If not exclusively, how about installed but 2.7 is still default? If you would prefer, I can create a PR.

**Comment by aptalca** [comment]
No need to add python3 if it's not going to be used. When sab supports python3, we'll switch.

**Comment by CHBMB** [comment]
Posting this to track progress

https://github.com/sabnzbd/sabnzbd/issues/1203

**Comment by fbruffaert** [comment]
Would it be possible to ship this image with python3?
Most people use nzbToMedia, which require py3. Since the scripts are executed by sabnzbd, the script will fail. I have created a .sh script which launches the script with py3 but I had to install py3 manually on the container, so it won't survive to an image update.

**Comment by aptalca** [comment]
@fbruffaert see here for how to customize our containers: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by noaho** [comment]
Yeah, all of my nzbtomedia installs started failing today too. Python3 would be great!

**Comment by noaho** [comment]
FWIW there is a python3 branch of sabnzbd that appears to work, see for example: https://github.com/sabnzbd/sabnzbd/issues/1242

**Comment by sanderjo** [comment]
> Yeah, all of my nzbtomedia installs started failing today too. Python3 would be great!

You can solve that:

https://forums.sabnzbd.org/viewtopic.php?f=2&t=24563#p120085

**Comment by sanderjo** [comment]
> No need to add python3 if it's not going to be used. When sab supports python3, we'll switch.

There is PPA for sabnzbd-py3: https://forums.sabnzbd.org/viewtopic.php?f=16&t=24447
I've been using this for all my downloads for the past months, and it works.

Question: are you willing to support this? I'm creating an altered Dockerfile that uses it.
If not: are you willing to support it as soon as @Safihre declares it alpha?

**Comment by thelamer** [comment]
I think a tiered transition would be more prudent , I added a python3 branch that can be pulled with the tags in this report. 
https://lsio-ci.ams3.digitaloceanspaces.com/lsiodev/sabnzbd/2.3.9-0ubuntu1jcfp218.04-pkg-ed9a3ac9-dev-e5b0fdbc5e0a189f4213a6c9b662f7d5f6788e5c/index.html

It does not do anything special, we just install python3 along with python2 and the same pip modules , will this work for the time being until a full switch to python3 can be vetted ? 

Reaching out here for testers .

**Comment by sanderjo** [comment]
Ah, that is fast. I have to find out how that works.

In the meantime: this is needed in the Dockerfile to create the image that provides sabnzbdplus with python3, based on the PPA by @jcfp:

```
RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:jcfp/private &&  apt-get install -y sabnzbdplus unzip

CMD env LANG=C.UTF-8 sabnzbdplus -b0 --server 0.0.0.0:8080
```

**Comment by nitrag** [comment]
Thanks @thelamer. I have been using your same "over the top" method for the last month in my own custom image and it's been working fine. I will test your docker image to confirm.

**Comment by sanderjo** [comment]
> @fbruffaert see here for how to customize our containers: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

Ah ... ! Cool, with my own shell-script installing sabnzbd-py3 from PPA in `/config/custom-cont-init.d/`  I got sabnzbd-python3 working within the existing linuxserver sabnzbd image!

Within the Dockerfile I added
```
RUN mkdir /config/custom-cont-init.d
COPY ./install-sabnzbd-python3.sh /config/custom-cont-init.d/
RUN ls -al /config/custom-cont-init.d/
```

with the contents of `install-sabnzbd-python3.sh` being:
```
#!/bin/sh
echo "Installing sabnzbd-py3:"
apt-get update
apt-get install -y software-properties-common
add-apt-repository ppa:jcfp/private
apt-get update
apt-get -y dist-upgrade
echo "Done installing sabnzbd-py3"
```

Then the usual
```
docker build   --no-cache   --pull   -t linuxserver/sabnzbd:latest .
```
and then
```
docker run  -p 8080:8080  -p 9090:9090  linuxserver/sabnzbd:latest
```
... which takes a minute or so installing the sabnzbd-python3 stuff, and then:

```
...
Done installing sabnzbd-py3
[custom-init] install-sabnzbd-python3.sh: exited 0
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.


2020-01-03 21:27:48,872::INFO::[sabnzbdplus:1097] --------------------------------
2020-01-03 21:27:48,873::INFO::[sabnzbdplus:1098] sabnzbdplus-3.0.0-develop (rev=unknown)
2020-01-03 21:27:48,873::INFO::[sabnzbdplus:1099] Full executable path = /usr/bin/sabnzbdplus
2020-01-03 21:27:48,873::INFO::[sabnzbdplus:1109] Platform = posix
2020-01-03 21:27:48,874::INFO::[sabnzbdplus:1110] Python-version = 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
2020-01-03 21:27:48,874::INFO::[sabnzbdplus:1111] Arguments = /usr/bin/sabnzbdplus --config-file /config --server 0.0.0.0:8080
2020-01-03 21:27:48,874::INFO::[sabnzbdplus:1114] Preferred encoding = UTF-8
2020-01-03 21:27:48,874::INFO::[sabnzbdplus:1121] SSL version = OpenSSL 1.1.1  11 Sep 2018
```

Tada: sabnzbdplus-3.0.0-develop is running, of course with python3!

**Comment by sanderjo** [comment]
With bit more hacked code based on reverse engineering, the install time (and thus time-to-boot) is now down to 30 seconds:

```
#!/bin/sh
echo "Installing sabnzbd-py3:"
#apt-get update
#apt-get install -y software-properties-common
#add-apt-repository ppa:jcfp/private
# As jcfp's PPA's are trusted (key already added), this will work:
echo "deb http://ppa.launchpad.net/jcfp/private/ubuntu bionic main" >> /etc/apt/sources.list.d/jcfp-ubuntu-private-bionic.list 
apt-get update
apt-get -y dist-upgrade
echo "Done installing sabnzbd-py3"
```

**Comment by thelamer** [comment]
The python3 stack is now installed on the base `latest` tag. 
And the `unstable` tag is not python3 only. 

I will be closing this issue out as a full swap to python3 on the latest tag will likely take some time.
