### ISSUE TITLE
Six Module Missing

### ISSUE THREAD

**Issue by ngonzal** [linuxserver/docker-sabnzbd#7]
After a reboot and starting up the container I'm seeing a lot of messages about a missing six module:

```
ImportError: No module named six
Traceback (most recent call last):
  File "/usr/bin/sabnzbdplus", line 55, in <module>
    import cherrypy
  File "/usr/share/sabnzbdplus/cherrypy/__init__.py", line 64, in <module>
    from cherrypy._cperror import HTTPError, HTTPRedirect, InternalRedirect
  File "/usr/share/sabnzbdplus/cherrypy/_cperror.py", line 122, in <module>
    import six
```

I rebuilt the image with an extra line installing python-six(&& apt-get install python-six) and things are working now.

**Comment by sparklyballs** [comment]
yeah, i've been looking at it too.



they've ballsed it completely though, if it's a requirement then it should be called when sab is pulled from the ppa.

**Comment by sparklyballs** [comment]
current advice is to set any value for the variable 
ADVANCED_DISABLEUPDATES

to disable updates and stay on the version that's currently in the container.

**Comment by sparklyballs** [comment]
fixed in later release contained in container.
