### ISSUE TITLE
On first run the download folders are incorrect

### ISSUE THREAD

**Issue by sspilleman** [linuxserver/docker-sabnzbd#71]
## Expected Behavior
Volume mapping ensures that the download location + incomplete download location is correctly mapped inside the container

## Current Behavior
The downloads are written to the config directory Downloads/in(complete) which IN the container is inside the config folder.
I had to manually correct this by changing it in the sabnzbd.ini file to point to /downloads/incomplete and /downloads (in the sabnzbd.ini the were Downloads/incomplete and Downloads.complete

**Comment by aptalca** [comment]
That needs to be set by the user in the gui settings (in the wizard). You can use whatever path mappings you like for the downloads. We suggest `/download`

**Comment by royduin** [comment]
Maybe add this to the readme?

**Comment by albino1** [comment]
I spent so much time trying to solve this.  Once you know, the answer is really simple, but it's not written down anywhere.  It was only through trial and error and then one random internet post by a guy that I was able to finally understand how to fix it:

***After the SABnzbd wizard has run*** you have to manually change the folders ***in the SABnzbd GUI*** specifically to `/incomplete-downloads` and `/downloads` by going to `Settings -> Folders -> User Folders`.

Once you do that everything downloads to the correct location.

If you could please add this to the readme instructions I think it would solve a lot of headache, as some googling tells me that a lot of people have encountered this problem.  Thanks.

**Comment by aptalca** [comment]
It's already in the readme: https://github.com/linuxserver/docker-sabnzbd#application-setup

**Comment by albino1** [comment]
Wow, you're right.  I'm sorry, consider this user error on my part.  I can't believe I didn't even find that while googling, let alone when I read through the page on the docker hub a half dozen times.

Apologies for bumping this closed issue, and keep up the good work.
