### ISSUE TITLE
cannot run script nzbToMedia.py

### ISSUE THREAD

**Issue by gregpetersde** [linuxserver/docker-sabnzbd#72]
Hello,

Docker is a new concept for me and I need some help. I could not find the solution in any forum, tutorial etc. so far.

I have an ubuntu 18.04 LTS machine running sickchill and sabnzbd without any problems, but the configuration itself is a bit oversized and not ideal. So I decided to set up a completely new system based on a PI4 with OMV5 and Docker. 

I was able to deploy the containers `linuxserver/sabnzbd:latest` and `linuxserver/sickchill:latest` without major problems: sickchill and sabnzbd work as expected (i.e. exactly as expected from my ubuntu 18.04 LTS machine).

The only thing I didn't get to work is nzbToMedia: I just can't get sabnzbd to run the postprocessing script nzbToMedia.py. After downloading a nzb, sabnzbd gives the following error message: "**Exit(-1) Cannot run script /config/scripts/nzbToMedia/nzbToMedia.py**".

These are the steps I tried to so far:
1) I set `PUID` and `GUID` according to the user `pi`, ie `1000` and `1000`, resp
2) as user pi, i created a sub-dir to `/config` called `/scripts`
3) I cd'ed into the /config/scripts/ and installed via git `git clone https://github.com/clinton-hall/nzbToMedia.git`
4) I changed `autoProcessMedia.cfg` according to the changes I made on my ubuntu 18.04 LTS
5) I made the nzbToMedia.py script executable by `sudo chmod +x nzbToMedia.py`
6) I checked that the directory is owned by `pi` resp that `pi` has all the permissions:
    `pi@omv:/srv/dev-disk-by-label<LABEL>/config/sabnzbd/scripts $ ls -la`
    `total 24`
    `drwxrwxrwx+ 3 pi pi    4096 Mar 24 16:40 .`
    `drwxrwxrwx+ 6 pi users 4096 Mar 24 20:19 ..`
   ` drwxrwxrwx+ 8 pi pi    4096 Mar 24 20:09 nzbToMedia`
7) In the config of sabnuzbd i set similar settings as on my ubuntu machine

I'm stuck! I don't understand why sabnzbd does not even run the script (that's at least my understanding of the error message). Do I have to change something in the header of `nzbToMedia.py`?

Currently it reads:
`#!/usr/bin/env python`
`# coding=utf-8`

If I check python in OMV with `which python` I get `/usr/bin/python`, which is the same as on my ubuntu machine.

Best, Markus

**Comment by morganzero** [comment]
I'm bumping this thread. I enounter the exact same issue as @gregpetersde

**Comment by gregpetersde** [comment]
Couldn't figure it out on my own. I'm now using docker-sonarr together with docker-sabnzbd, which does require post-scripts (as fas as I understand it, sonarr is able to directly communicating with sabnzbd, nzbget, etc. over APO, for both, download and failed download handling).

Sorry! Markus

**Comment by clinton-hall** [comment]
I have just had this issue posted for nzbToMedia https://github.com/clinton-hall/nzbToMedia/issues/1767

This user is finding that `python` is not a recognized command, but python3 is.
Is this standard, or is something broken?

**Comment by aptalca** [comment]
@clinton-hall we are slowly switching this image over to py3 as sab3 supports py3.
Currently, there is no py2 in there, but python-pip is used during build. When we fully remove all py2 bits (very soon), we'll symlink `/usr/bin/python` to `/usr/bin/python3` as we do in the `unstable` tag

**Comment by clinton-hall** [comment]
@aptalca 
Perfect, thanks for the explanation.

**Comment by aptalca** [comment]
@gregpetersde @clinton-hall new version of sab image just pushed. Py2 is removed and `python` is symlinked to `python3`
