### ISSUE TITLE
ppa for the unstable branch

### ISSUE THREAD

**Issue by jcfp** [linuxserver/docker-sabnzbd#74]
Support for the sabnzbdplus package published on my not-so-"private" ppa has reached its expiry date. No more updates will be made there, and the aforementioned package and its dependencies deleted in due course.

Feel free to switch the unstable branch of your docker back to my [regular ppa](https://launchpad.net/~jcfp/+archive/ubuntu/ppa), which now has 3.0.0 alpha1 for ubuntu 18.04/bionic (and newer) and will continue to see updates.

**Comment by aptalca** [comment]
@jcfp thanks so much for the heads up. We'll change that.

Also thanks for maintaining the ppa
