### ISSUE TITLE
Add python module requirements for nzb-notify

### ISSUE THREAD

**Issue by Do-while-Bacon** [linuxserver/docker-sabnzbd#79]
Since Sabnzbd's own wiki page recommends using the popular NZB-Notify script to extended support for notifications (e.g. Discord, Slack, PushBullet...etc), would it be possible to include the required modules within the docker container? Specifically, the missing ones appear to be:

setuptools
pynzbget
six

Perhaps even the NZB-Notify script itself could also be included with the container? I don't know if this would violate some kind of best practices for building docker containers, so, I apologize in advance if this request is inappropriate.

Thanks!

**Comment by aptalca** [comment]
May be a suitable candidate for a docker mod

**Comment by luke255** [comment]
Current status as far as I can see - The `nzb-notify` script recommended by SABnzbd doesn't work with the [apprise docker mod](https://github.com/linuxserver/docker-mods/tree/universal-apprise) as is. Here are the steps required:

- Add the apprise docker mod to SABnzbd. If you want to double check this worked, run `command -v apprise` in the container. It should return the path to `apprise`
- Run `python3 -m pip install pynzbget` within the container to install a required dependency
- Create a `scripts` folder in `/config` (if not already present).
- Clone the [nzb-notify](https://github.com/caronc/nzb-notify) repo _contents_ into `scripts`, **cloning into a subfolder of `scripts` won't work.** The container doesn't have `git` by default so you can do this on your host within the folder `/config` is mapped to, or simply download a ZIP of the repo
- In the "Folders" section of SABnzb's settings, set the "Scripts Folder" to `/config/scripts`
- Configure `nzb-notify` as per [the README](https://github.com/caronc/nzb-notify#sabnzbd-users), skipping the "Installation Instructions"

The only problem with this is that when the container is updated/recreated the `pynzbget` dependency will need manually reinstalling. I suppose it may be possible to automate this with the cron mod but that could be a little messy!

I'll raise an issue on the mod repo, though it could be the `nzb-notify` script that needs changing. Equally, this repo may need some changes as the dependency won't be needed on other containers using the mod. Perhaps someone can point me in the right direction?

Either way, I thought this might be useful for anyone like me who came here from Google.

**Comment by aptalca** [comment]
You can use a custom script to make your changes permanent: 
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by Diegus83** [comment]
This is the script that I made back in August 2020 and it has been working for me so far, I will leave it here in case it helps others. I saved as 'sabnzbd-notify-requirements.sh' in the 'custom-cont-init.d' directory.

`#!/bin/bash
echo "**** check for nzb-notify ****"
FILE=/config/scripts/requirements.txt
if [ -f "$FILE" ]; then
    echo "nzb-notify already downloaded"
else
	echo "**** get nzb-notify lastest version ****"
	cd /config/
	mkdir scripts
	cd scripts
	curl https://codeload.github.com/caronc/nzb-notify/zip/master -o nzb-notify-master.zip

	echo "**** check for and installing unzip ****"
	if ! command -v unzip &> /dev/null
	then
	    echo "unzip could not be found"
	    apt-get update
		apt-get -y install zip
	fi

	echo "**** unzip contents ****"
	unzip -o -d . nzb-notify-master.zip

	echo "**** cleanup ****"
	mv nzb-notify-master/* ./
	rm -r nzb-notify-master
	rm nzb-notify-master.zip
fi

echo "**** installing nzb-notify requirements ****"
pip install -r /config/scripts/requirements.txt

echo "**** done ****"
exit`

**Comment by Do-while-Bacon** [comment]
@Diegus83 That script worked perfectly for me. Thanks for sharing!

**Comment by DrSeussFreak** [comment]
@Diegus83 - thank-you, this worked like a charm!!!

**Comment by Diegus83** [comment]
@Do-while-Bacon @DrSeussFreak You are welcome!
I put the script in a [repository ](https://github.com/Diegus83/sabnzbd-notify-requirements.sh)along with the install instructions, maybe it will make it easier for other folks to find it.
