### ISSUE TITLE
Is there a good way to get v3 yet?

### ISSUE THREAD

**Issue by a10kiloham** [linuxserver/docker-sabnzbd#80]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

V3 now stable but latest not pulling - newest release avail is still a rc
## Current Behavior

Latest is 2.3.9
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by aptalca** [comment]
We pull from this repo: https://launchpad.net/~jcfp/+archive/ubuntu/nobetas

When 3.0 for bionic is published there, our ci will publish an image within an hour or two
