### ISSUE TITLE
Use requirements.txt instead of PPA

### ISSUE THREAD

**Issue by Safihre** [linuxserver/docker-sabnzbd#81]
SABnzbd-maintainer here.
We are experiencing [some issues](https://github.com/sabnzbd/sabnzbd/issues/1577) because the provided version of `cherrypy` in the Ubuntu repositories is outdated (3 years).
This made me wonder if it wouldn't be better for the Docker to not use the PPA but install the `requirements.txt` manually and run `python3 SABnzbd.py` manually?
We do the same for our CI/CD-pipeline: https://github.com/sabnzbd/sabnzbd/blob/develop/.travis.yml#L29-L32
Only use the PPA for the `unrar p7zip-full par2` packages.

I am not an active Docker-user, so maybe this won't work. But I would like for the Docker to at least be similar to what I as developer intended to be used 💯

**Comment by aptalca** [comment]
@Safihre thanks for the heads up. We weren't aware of that issue. I'll look into switching over

**Comment by aptalca** [comment]
@Safihre here's a PR for the unstable (pre-release) tag: #83 

I did notice something strange, though. If we don't specifically install python3-six, sab gives an error during start and complains about lack of six. Recent sab commits show that six dependency was recently removed. Any ideas?

**Comment by Safihre** [comment]
Great!
`six` is a depency of `cheroot` which is a depency of `cherrypy`. Although for the time being we list `cheroot` specifically in `requirements.txt` due to e bug in their most recent version.

**Comment by aptalca** [comment]
Ah, gotcha. It's side effect of us trying to slim down the image size. The python3-pip package installs python3-six as a dependency. When we use pip install, it skips six because it's already there. When we later remove python3-pip due to its hundreds of MBs of dependencies, it removes python3-six along with it, unless we specifically install it.
