### ISSUE TITLE
Deobfuscate.py fails after upgrade to 3.0.2-LS71

### ISSUE THREAD

**Issue by dajappie** [linuxserver/docker-sabnzbd#88]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

After upgrading my sabnzbd docker image from 3.0.1-ls70 to 3.0.2-ls71, the Deobfuscate.py script fails with a Python error. Looks like the used script version doesn't adhere to Python coding standards.

------------------------------

## Expected Behavior
Deobfuscate.py should execute without errors

## Current Behavior
Deobfuscate.py fails with a Python error message (below) and doesn't perform the filename deobfuscation.

`File "/config/scripts/Deobfuscate.py", line 57
print "This script needs to be called from SABnzbd as post-processing script."
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("This script needs to be called from SABnzbd as post-processing script.")?`

## Steps to Reproduce
1. Set Deobfuscate.py as postprocessing script for a profile
2. Download a NZB on that profile
3. Error occurs

## Environment
**OS:** Synology DS218+ with DSM 6.2.3
**CPU architecture:** x86_64
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
`docker run -d \
--name sabnzbd \
--restart unless-stopped \
-v /volume1/docker/sabnzbd:/config \
-v /volume1/video/Downloads:/downloads \
-v /volume1/video/Downloads/incomplete-downloads:/incomplete-downloads \
-v /volume1/video/Downloads/watched:/watched \
-e PUID=1024 \
-e PGID=101 \
-e TZ=Europe/Amsterdam \
-p 8082:8080 \
linuxserver/sabnzbd:3.0.2-ls71`

## Docker logs
Nothing showing in docker log from Syno frontend, only in sabnzbd frontend.

**Comment by carazzim0** [comment]
see https://github.com/linuxserver/docker-sabnzbd/issues/72#issuecomment-676537753

python2 is EOL and was removed

**Comment by dajappie** [comment]
Fix is simple:
- Enter docker bash: `docker exec -it sabnzbd /bin/bash`
- Install tool 2to3 for Python v2 to v3 conversion: `pip install 2to3`
- Run tool on existing script: `2to3 -w /config/scripts/Deobfuscate.py`

**Comment by Safihre** [comment]
A python3 compatibile version of `Defobfuscate.py` is included with SABnzbd 3.x, so users can use that 👍
