### ISSUE TITLE
Latest image is complaining about port 8080 not being available.

### ISSUE THREAD

**Issue by MynMac** [linuxserver/docker-sabnzbd#89]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

sabnzbd     |
sabnzbd     | Fatal error:
sabnzbd     |   Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.
sabnzbd     |
sabnzbd     | Fatal error:
sabnzbd     |   Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by aptalca** [comment]
#82
