### ISSUE TITLE
Forced port 8080

### ISSUE THREAD

**Issue by SunMar** [linuxserver/docker-sabnzbd#90]
Hi,

Today I was setting up SABnzbd and ran into a minor issue in the Setup Wizard (sabnzbd/sabnzbd#1617). This triggered me to update the default port in the SABnzbd configuration to match the port I was mapping to the container, but SABnzbd kept reverting back to 8080. After some digging I found #2 and #40 which shed some light on this.

https://github.com/linuxserver/docker-sabnzbd/blob/6aab65f0a8c38ad0b68bf0b93928729f0cd7b41d/root/etc/services.d/sabnzbd/run#L3-L5

So because of the `--server 0.0.0.0:8080` argument the default port is always forced to 8080 and you can't change it in the configuration (or rather you can change it, but it'll reverted back to 8080 as soon as you try to apply the change and restart the container).

I am curious as to what exactly is the reason the container needs to be forced to use port 8080? That unfortunately is never explained in #2 or #40. Wouldn't `--server 0.0.0.0` also work for binding to all interfaces (https://sabnzbd.org/wiki/advanced/command-line-parameters and https://sabnzbd.org/wiki/configuration/3.0/general), and then if someone wants to change the port they'll be able to do so? I don't see any `HEALTHCHECK` or something like that configured so I am wondering what would break if you don't use 8080 :).

If the forced port 8080 needs to stay, is it possible to add a note in the README explicitly stating that the default port can't be changed?

Also in the README it says:
```
Https access for sabnzbd needs to be enabled in either the intial setup wizard or in the configure settings of the webui, be sure to use 9090 as port for https.
```

This text confuses me a bit. In the way it's written I would interpret that has "HTTPS is required" and "You can only use port 9090, not any other port". But either of those is I think false, HTTP seems to work fine and HTTPS from a port other than 9090 also seems to work fine. Maybe that can be clarified a bit too? :)

Thank you for all the work in providing this container!

**Comment by Roxedus** [comment]
This is not the only image we explicit bind on startup, we actually do that quite often. There is multiple reasons behind this, a huge motivator is support. The *correct* way to use another port, would be to map that port to port 8080, ie `-p 9000:8080`

I agree, the https part very unclear, I am not against straight up removing that paragraph.

**Comment by SunMar** [comment]
@Roxedus yeah I agree using `-p 9000:8080` is a better approach, but that does assumes the upstream package (SABnzbd) understands that the port it's being accessed on is not necessarily the same port that's in the configuration file. Some links in the Setup Wizard actually break if you remap 8080 to a different port. Luckily it seems like the Setup Wizard is the only place this breaks and it doesn't prevent you from completing it, so it's not a big deal. I created an upstream ticket for that, I think it's something to fix in SABnzbd, not an issue with the container :).

Hence my suggestion to mention it in the README, that would've saved me close to an hour of figuring out what was going on :). If you want I can make a quick PR for that. Remove the HTTPS paragraph and put in that port 8080 is forced and can't be changed.

**Comment by Roxedus** [comment]
I don't think mentioning that the port cant be changed is needed, as that is the case for most of our containers. A note regarding the wizard might be a play, unless sab completely redesigns how to build that link

**Comment by SunMar** [comment]
@Roxedus Other than SABnzbd I have also setup NZBGet, Medusa, Sonarr, Radarr, and Bazarr. None of those force the listening interface or port, changing the port on them (and then updating the `-p` for Docker) worked fine. I usually align the internal and external ports just to avoid potential issues, even though from a technical point of view it shouldn't be necessary. That's why I was so surprised when I started setting up SABnzbd it suddenly didn't work. And also there were two other tickets (#2 and #40) about this as well, so though rare I'm not the only one running into this :).

Adding a note about the Setup Wizard would be useful too if SABnzbd can't fix it on their side, but I'm hoping it can be a minor change by just making the links relative instead of absolute (like the rest of the UI).

**Comment by schevalley20** [comment]
@Roxedus As an FYI, the default "--server 0.0.0.0:8080" does interfere with running this on vmware's virtual container host, at least when configured to use a dedicated container network.  Removing the --server option resolves the issue and allows sabnzbd to use the parameters specified in the config file.

**Comment by aptalca** [comment]
But there is no config file when the container is first created, is there?

**Comment by SunMar** [comment]
@aptalca yes, that's why you do need `--server 0.0.0.0` (the default is `127.0.0.1` and that would make SABnzbd inaccessible), but it's not needed to also force the port to `8080`, just `--server 0.0.0.0` without the `:8080` is enough. the default port is already `8080` and then changing it in the configuration works

**Comment by avalon2021** [comment]
I agree about the initial container creation, but would it be possible to add environment variables for server and port that can be specified if desired and if not specified the default 0.0.0.0:8080 would be used?  Just a thought.

Ultimately, in my use case its really just a bug or "feature" of vmware's implementation of the docker api in the virtual container host.

**Comment by aptalca** [comment]
That is really an edge case, therefore you're better off using custom script that simply `sed`s the service file and changes it.

See here: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by avalon2021** [comment]
That is perfect!  Thanks!

**Comment by PaPaTheGMan** [comment]
I'd appreciate re-opening this issue.  The latest image seems to revert back to forcing 0.0.0.0:8080 regardless of what I put in the setting screen.  This causes my connection to Sonarr to be broken.  Thank you.

**Comment by PaPaTheGMan** [comment]
This has not been fixed.  Sonarr still forces 0.0.0.0:8080 regardless of what I put in the setting screen. This continues to cause my connection to Sonarr to be broken and unusable. Thank you.

**Comment by j0nnymoe** [comment]
I'm not entirely sure how forcing the port to 8080 is breaking Sonarr. As if you're using docker networking, you could just reference `sabnzbd` as the address then port 8080 and it'll work.

**Comment by PaPaTheGMan** [comment]
My SABnzbd server is on a different machine than Sonarr.  That server already as an unmovable process taking up 8080.  When I tell Sonarr to find SABnzbd on the new port I attempted to assign, SABnzbd refuses the connection.  This is even though I can directly attach to SABnzbd through the newly assigned port.

**Comment by SunMar** [comment]
@PaPaTheGMan if you want sabnzb to be connectable on a different port, you need to change the way how you launch the docker container. See https://github.com/linuxserver/docker-sabnzbd#parameters

So for example if you want sabnzb to be connectable from the outside on port 12345 just start the docker container with `-p 12345:8080`. Do not change the port 8080 in the sabnzb configuration, that is for different purposes. Remember that running a Docker container is like running a virtual machine. In the configuration settings you are controlling what is happening inside that virtual machine, not how the outside connects to that virtual machine. How the outside (in your case Sonarr) connects needs to be handled in how you launch your Docker container.

**Comment by PaPaTheGMan** [comment]
Thanks for responding, but that's exactly how I have it set.  Sonarr still complains that it can't find SABnzbd.
